/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "memoria_operor/memoria_operor.h"
#include <stdint.h>
#include <stdio.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_the_helpers_this_suite_relies_on_are_themselves_right(void);
extern void test_the_forward_copy_lands_every_byte_at_every_alignment(void);
extern void test_the_fill_writes_every_byte_at_every_alignment(void);
extern void test_the_upward_move_carries_overlapping_bytes(void);
extern void test_the_downward_move_carries_overlapping_bytes(void);
extern void test_the_compare_orders_two_regions_by_their_first_difference(void);
extern void test_the_search_returns_the_first_occurrence(void);
extern void test_a_byte_past_the_count_takes_no_part_in_either_scan(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/accuracy/test_memoria_operor_accuracy\\test_memoria_operor_accuracy.c");
  run_test(test_the_helpers_this_suite_relies_on_are_themselves_right, "test_the_helpers_this_suite_relies_on_are_themselves_right", 167);
  run_test(test_the_forward_copy_lands_every_byte_at_every_alignment, "test_the_forward_copy_lands_every_byte_at_every_alignment", 202);
  run_test(test_the_fill_writes_every_byte_at_every_alignment, "test_the_fill_writes_every_byte_at_every_alignment", 246);
  run_test(test_the_upward_move_carries_overlapping_bytes, "test_the_upward_move_carries_overlapping_bytes", 290);
  run_test(test_the_downward_move_carries_overlapping_bytes, "test_the_downward_move_carries_overlapping_bytes", 337);
  run_test(test_the_compare_orders_two_regions_by_their_first_difference, "test_the_compare_orders_two_regions_by_their_first_difference", 388);
  run_test(test_the_search_returns_the_first_occurrence, "test_the_search_returns_the_first_occurrence", 445);
  run_test(test_a_byte_past_the_count_takes_no_part_in_either_scan, "test_a_byte_past_the_count_takes_no_part_in_either_scan", 503);

  return UNITY_END();
}
