/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "locus_carcerum/locus_carcerum.h"
#include <stdint.h>
#include <stdio.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_the_pattern_helpers_this_suite_relies_on_are_themselves_right(void);
extern void test_persistent_cells_never_share_a_byte(void);
extern void test_a_reused_cell_does_not_disturb_its_neighbors(void);
extern void test_the_two_tiers_never_hand_out_the_same_byte(void);
extern void test_a_maximum_security_release_leaves_zeros(void);
extern void test_a_maximum_security_rewind_zeros_everything_taken_since_the_mark(void);
extern void test_a_rewind_to_a_mark_gives_back_every_byte_taken_since_it(void);
extern void test_two_prison_sites_hold_no_byte_in_common(void);
extern void test_the_rounding_lands_on_the_next_whole_word(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/accuracy/test_locus_carcerum_accuracy\\test_locus_carcerum_accuracy.c");
  run_test(test_the_pattern_helpers_this_suite_relies_on_are_themselves_right, "test_the_pattern_helpers_this_suite_relies_on_are_themselves_right", 222);
  run_test(test_persistent_cells_never_share_a_byte, "test_persistent_cells_never_share_a_byte", 254);
  run_test(test_a_reused_cell_does_not_disturb_its_neighbors, "test_a_reused_cell_does_not_disturb_its_neighbors", 303);
  run_test(test_the_two_tiers_never_hand_out_the_same_byte, "test_the_two_tiers_never_hand_out_the_same_byte", 367);
  run_test(test_a_maximum_security_release_leaves_zeros, "test_a_maximum_security_release_leaves_zeros", 424);
  run_test(test_a_maximum_security_rewind_zeros_everything_taken_since_the_mark, "test_a_maximum_security_rewind_zeros_everything_taken_since_the_mark", 459);
  run_test(test_a_rewind_to_a_mark_gives_back_every_byte_taken_since_it, "test_a_rewind_to_a_mark_gives_back_every_byte_taken_since_it", 507);
  run_test(test_two_prison_sites_hold_no_byte_in_common, "test_two_prison_sites_hold_no_byte_in_common", 538);
  run_test(test_the_rounding_lands_on_the_next_whole_word, "test_the_rounding_lands_on_the_next_whole_word", 595);

  return UNITY_END();
}
