/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "verba_scribo/verba_scribo.h"
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_the_references_this_suite_relies_on_behave_as_assumed(void);
extern void test_the_base_ten_entries_match_the_reference(void);
extern void test_the_padded_and_based_entries_match_the_reference(void);
extern void test_a_double_written_at_seventeen_digits_reads_back_the_same(void);
extern void test_a_double_written_at_fewer_digits_stays_inside_the_allowed_error(void);
extern void test_the_fixed_form_matches_the_reference(void);
extern void test_an_exact_tie_rounds_up(void);
extern void test_the_text_entries_write_the_bytes_they_are_documented_to(void);
extern void test_the_non_finite_forms_and_the_predicates(void);
extern void test_a_run_of_entries_threads_the_cursor(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/accuracy/test_verba_scribo_accuracy\\test_verba_scribo_accuracy.c");
  run_test(test_the_references_this_suite_relies_on_behave_as_assumed, "test_the_references_this_suite_relies_on_behave_as_assumed", 159);
  run_test(test_the_base_ten_entries_match_the_reference, "test_the_base_ten_entries_match_the_reference", 200);
  run_test(test_the_padded_and_based_entries_match_the_reference, "test_the_padded_and_based_entries_match_the_reference", 277);
  run_test(test_a_double_written_at_seventeen_digits_reads_back_the_same, "test_a_double_written_at_seventeen_digits_reads_back_the_same", 341);
  run_test(test_a_double_written_at_fewer_digits_stays_inside_the_allowed_error, "test_a_double_written_at_fewer_digits_stays_inside_the_allowed_error", 397);
  run_test(test_the_fixed_form_matches_the_reference, "test_the_fixed_form_matches_the_reference", 467);
  run_test(test_an_exact_tie_rounds_up, "test_an_exact_tie_rounds_up", 506);
  run_test(test_the_text_entries_write_the_bytes_they_are_documented_to, "test_the_text_entries_write_the_bytes_they_are_documented_to", 548);
  run_test(test_the_non_finite_forms_and_the_predicates, "test_the_non_finite_forms_and_the_predicates", 603);
  run_test(test_a_run_of_entries_threads_the_cursor, "test_a_run_of_entries_threads_the_cursor", 656);

  return UNITY_END();
}
