// memmanager - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Generated by tools/dev_env/gen_pow5.py. Editing this by hand is undone the next time anyone
// runs the generator, and `harness.py generated` will say so before that happens.
#ifndef MMGR_POW5_H
#define MMGR_POW5_H

#include "mmgr_config.h"

MMGR_BEGIN_DECLS

/**
 * @file pow5.h
 * @brief The powers of five a decimal conversion needs.
 *
 * A decimal value is mant * 10^ex. Ten to the ex is five to the ex times two to the ex, and the
 * twos are free: a power of two is the exponent field, so applying one is an add to that field
 * and cannot round. Only the fives need carrying, and they are the same numbers every time.
 *
 * Each entry is five to a power of two as a 128 bit fraction with the top bit set, beside the
 * binary exponent that goes with it. Any exponent below 512 is the product of at most nine of
 * them, so the loop that used to run four hundred times runs nine.
 *
 * The reciprocals are the second table. A negative exponent multiplies by one of those rather
 * than dividing, and division is the one operation this library does not want in a hot path.
 *
 * Truncated, not rounded. A truncated entry is never above the true power, so a product is
 * never above the true product, and the bit that decides a tie is never wrongly clear.
 */

/** @brief How many doublings the tables carry. */
#define MMGR_POW5_STEPS 9

/** @brief Largest decimal exponent the tables can reach. */
#define MMGR_POW5_MAX ((1 << MMGR_POW5_STEPS) - 1)

/** @brief One power of five: a 128 bit fraction, top bit set, and its binary exponent. */
typedef struct
{
    mmgr_u64 hi;
    mmgr_u64 lo;
    int e2;
} MmgrPow5;

/** @brief Five to the power of two of the index. */
static const MmgrPow5 mmgr_pow5_up[MMGR_POW5_STEPS] = {
    {0xA000000000000000ULL, 0x0000000000000000ULL, -125}, /* 5^1   */
    {0xC800000000000000ULL, 0x0000000000000000ULL, -123}, /* 5^2   */
    {0x9C40000000000000ULL, 0x0000000000000000ULL, -118}, /* 5^4   */
    {0xBEBC200000000000ULL, 0x0000000000000000ULL, -109}, /* 5^8   */
    {0x8E1BC9BF04000000ULL, 0x0000000000000000ULL, -90},  /* 5^16  */
    {0x9DC5ADA82B70B59DULL, 0xF020000000000000ULL, -53},  /* 5^32  */
    {0xC2781F49FFCFA6D5ULL, 0x3CBF6B71C76B25FBULL, 21},   /* 5^64  */
    {0x93BA47C980E98CDFULL, 0xC66F336C36B10137ULL, 170},  /* 5^128 */
    {0xAA7EEBFB9DF9DE8DULL, 0xDDBB901B98FEEAB7ULL, 467},  /* 5^256 */
};

/** @brief And the reciprocals, so a negative exponent never divides. */
static const MmgrPow5 mmgr_pow5_down[MMGR_POW5_STEPS] = {
    {0xCCCCCCCCCCCCCCCCULL, 0xCCCCCCCCCCCCCCCCULL, -130}, /* 5^-1   */
    {0xA3D70A3D70A3D70AULL, 0x3D70A3D70A3D70A3ULL, -132}, /* 5^-2   */
    {0xD1B71758E219652BULL, 0xD3C36113404EA4A8ULL, -137}, /* 5^-4   */
    {0xABCC77118461CEFCULL, 0xFDC20D2B36BA7C3DULL, -146}, /* 5^-8   */
    {0xE69594BEC44DE15BULL, 0x4C2EBE687989A9B3ULL, -165}, /* 5^-16  */
    {0xCFB11EAD453994BAULL, 0x67DE18EDA5814AF2ULL, -202}, /* 5^-32  */
    {0xA87FEA27A539E9A5ULL, 0x3F2398D747B36224ULL, -276}, /* 5^-64  */
    {0xDDD0467C64BCE4A0ULL, 0xAC7CB3F6D05DDBDEULL, -425}, /* 5^-128 */
    {0xC0314325637A1939ULL, 0xFA911155FEFB5308ULL, -722}, /* 5^-256 */
};

MMGR_STATIC_ASSERT(MMGR_POW5_MAX >= 511, "the tables do not reach the exponents a double can carry");

MMGR_END_DECLS

#endif
