/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "proximus_operor/proximus_operor.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_proxim_header_is_self_contained(void);
extern void test_reads_at_every_alignment(void);
extern void test_each_width_reads_only_its_own_bytes(void);
extern void test_writes_round_trip_at_every_alignment(void);
extern void test_a_write_touches_exactly_its_width(void);
extern void test_aligned_entries_round_trip(void);
extern void test_the_aligned_word_and_the_unaligned_word_agree(void);
extern void test_the_bulk_move_word_round_trips(void);
extern void test_the_move_word_is_the_configured_width(void);
extern void test_read_copies_exactly_the_bytes_asked_for(void);
extern void test_read_of_nothing_writes_nothing(void);
extern void test_read_at_every_alignment(void);
extern void test_namespace_is_wired(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/proximus_operor/test_proximus_operor\\test_proximus_operor.c");
  run_test(test_proxim_header_is_self_contained, "test_proxim_header_is_self_contained", 22);
  run_test(test_reads_at_every_alignment, "test_reads_at_every_alignment", 27);
  run_test(test_each_width_reads_only_its_own_bytes, "test_each_width_reads_only_its_own_bytes", 46);
  run_test(test_writes_round_trip_at_every_alignment, "test_writes_round_trip_at_every_alignment", 56);
  run_test(test_a_write_touches_exactly_its_width, "test_a_write_touches_exactly_its_width", 73);
  run_test(test_aligned_entries_round_trip, "test_aligned_entries_round_trip", 82);
  run_test(test_the_aligned_word_and_the_unaligned_word_agree, "test_the_aligned_word_and_the_unaligned_word_agree", 94);
  run_test(test_the_bulk_move_word_round_trips, "test_the_bulk_move_word_round_trips", 105);
  run_test(test_the_move_word_is_the_configured_width, "test_the_move_word_is_the_configured_width", 114);
  run_test(test_read_copies_exactly_the_bytes_asked_for, "test_read_copies_exactly_the_bytes_asked_for", 119);
  run_test(test_read_of_nothing_writes_nothing, "test_read_of_nothing_writes_nothing", 135);
  run_test(test_read_at_every_alignment, "test_read_at_every_alignment", 143);
  run_test(test_namespace_is_wired, "test_namespace_is_wired", 163);

  return UNITY_END();
}
