/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "config/mmgr_config.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_types_header_is_self_contained(void);
extern void test_fixed_width_types_are_their_widths(void);
extern void test_word_matches_the_configured_width(void);
extern void test_index_fits_the_register_that_carries_it(void);
extern void test_packed_enum_keeps_its_declared_width(void);
extern void test_bool_constants(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/config/mmgr_types/test_mmgr_types\\test_mmgr_types.c");
  run_test(test_types_header_is_self_contained, "test_types_header_is_self_contained", 8);
  run_test(test_fixed_width_types_are_their_widths, "test_fixed_width_types_are_their_widths", 13);
  run_test(test_word_matches_the_configured_width, "test_word_matches_the_configured_width", 25);
  run_test(test_index_fits_the_register_that_carries_it, "test_index_fits_the_register_that_carries_it", 30);
  run_test(test_packed_enum_keeps_its_declared_width, "test_packed_enum_keeps_its_declared_width", 37);
  run_test(test_bool_constants, "test_bool_constants", 42);

  return UNITY_END();
}
