/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "confinium_exclusivum_infinitas/confinium_exclusivum_infinitas.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_init_refuses_bad_sizes(void);
extern void test_init_starts_empty_with_every_loculus_free(void);
extern void test_put_then_read_round_trips(void);
extern void test_put_refuses_more_than_vacant(void);
extern void test_read_takes_only_what_arrived(void);
extern void test_move_wraps_in_order(void);
extern void test_move_carries_every_length_at_every_offset(void);
extern void test_peek_leaves_the_tail_and_consume_moves_it(void);
extern void test_peek_holds_a_request_above_capacity(void);
extern void test_read_byte_empties_the_ring(void);
extern void test_loculus_next_picks_the_lowest_and_reports_empty(void);
extern void test_hold_takes_a_loculus_and_drop_returns_it(void);
extern void test_hold_refuses_a_loculus_that_does_not_exist(void);
extern void test_segments_publish_and_release_in_order(void);
extern void test_seg_at_walks_the_buffer(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/confinium_exclusivum_infinitas/test_infinitas\\test_infinitas.c");
  run_test(test_init_refuses_bad_sizes, "test_init_refuses_bad_sizes", 27);
  run_test(test_init_starts_empty_with_every_loculus_free, "test_init_starts_empty_with_every_loculus_free", 43);
  run_test(test_put_then_read_round_trips, "test_put_then_read_round_trips", 59);
  run_test(test_put_refuses_more_than_vacant, "test_put_refuses_more_than_vacant", 73);
  run_test(test_read_takes_only_what_arrived, "test_read_takes_only_what_arrived", 82);
  run_test(test_move_wraps_in_order, "test_move_wraps_in_order", 93);
  run_test(test_move_carries_every_length_at_every_offset, "test_move_carries_every_length_at_every_offset", 115);
  run_test(test_peek_leaves_the_tail_and_consume_moves_it, "test_peek_leaves_the_tail_and_consume_moves_it", 145);
  run_test(test_peek_holds_a_request_above_capacity, "test_peek_holds_a_request_above_capacity", 162);
  run_test(test_read_byte_empties_the_ring, "test_read_byte_empties_the_ring", 181);
  run_test(test_loculus_next_picks_the_lowest_and_reports_empty, "test_loculus_next_picks_the_lowest_and_reports_empty", 197);
  run_test(test_hold_takes_a_loculus_and_drop_returns_it, "test_hold_takes_a_loculus_and_drop_returns_it", 209);
  run_test(test_hold_refuses_a_loculus_that_does_not_exist, "test_hold_refuses_a_loculus_that_does_not_exist", 240);
  run_test(test_segments_publish_and_release_in_order, "test_segments_publish_and_release_in_order", 250);
  run_test(test_seg_at_walks_the_buffer, "test_seg_at_walks_the_buffer", 277);

  return UNITY_END();
}
