/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "clz/clz.h"
#include <stdint.h>
#include <stdio.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_the_exact_bit_scans_this_suite_relies_on_are_themselves_right(void);
extern void test_both_counts_are_right_at_every_single_bit_value(void);
extern void test_both_counts_are_right_at_every_pair_of_set_bits(void);
extern void test_both_counts_are_right_across_the_run_masks(void);
extern void test_both_counts_are_right_over_a_long_sweep_of_arbitrary_values(void);
extern void test_a_value_of_zero_gives_the_documented_count_from_both_calls(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/accuracy/test_clz_accuracy\\test_clz_accuracy.c");
  run_test(test_the_exact_bit_scans_this_suite_relies_on_are_themselves_right, "test_the_exact_bit_scans_this_suite_relies_on_are_themselves_right", 171);
  run_test(test_both_counts_are_right_at_every_single_bit_value, "test_both_counts_are_right_at_every_single_bit_value", 196);
  run_test(test_both_counts_are_right_at_every_pair_of_set_bits, "test_both_counts_are_right_at_every_pair_of_set_bits", 223);
  run_test(test_both_counts_are_right_across_the_run_masks, "test_both_counts_are_right_across_the_run_masks", 250);
  run_test(test_both_counts_are_right_over_a_long_sweep_of_arbitrary_values, "test_both_counts_are_right_over_a_long_sweep_of_arbitrary_values", 290);
  run_test(test_a_value_of_zero_gives_the_documented_count_from_both_calls, "test_a_value_of_zero_gives_the_documented_count_from_both_calls", 328);

  return UNITY_END();
}
