/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "ascii_persona_bitorum/ascii_persona_bitorum.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_ascii_header_is_self_contained(void);
extern void test_ascii_persona_bitorum_is_128_bits(void);
extern void test_ascii_class_numbering_is_pinned(void);
extern void test_ascii_num(void);
extern void test_ascii_alpha(void);
extern void test_ascii_alnum(void);
extern void test_ascii_upper(void);
extern void test_ascii_lower(void);
extern void test_ascii_hex(void);
extern void test_ascii_punct(void);
extern void test_ascii_space(void);
extern void test_ascii_print(void);
extern void test_ascii_ctrl(void);
extern void test_ascii_high_bytes_are_in_no_class(void);
extern void test_ascii_classes_partition_the_printables(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/ascii_persona_bitorum/test_ascii_persona_bitorum\\test_ascii_persona_bitorum.c");
  run_test(test_ascii_header_is_self_contained, "test_ascii_header_is_self_contained", 62);
  run_test(test_ascii_persona_bitorum_is_128_bits, "test_ascii_persona_bitorum_is_128_bits", 67);
  run_test(test_ascii_class_numbering_is_pinned, "test_ascii_class_numbering_is_pinned", 72);
  run_test(test_ascii_num, "test_ascii_num", 87);
  run_test(test_ascii_alpha, "test_ascii_alpha", 91);
  run_test(test_ascii_alnum, "test_ascii_alnum", 95);
  run_test(test_ascii_upper, "test_ascii_upper", 99);
  run_test(test_ascii_lower, "test_ascii_lower", 103);
  run_test(test_ascii_hex, "test_ascii_hex", 107);
  run_test(test_ascii_punct, "test_ascii_punct", 111);
  run_test(test_ascii_space, "test_ascii_space", 115);
  run_test(test_ascii_print, "test_ascii_print", 119);
  run_test(test_ascii_ctrl, "test_ascii_ctrl", 123);
  run_test(test_ascii_high_bytes_are_in_no_class, "test_ascii_high_bytes_are_in_no_class", 128);
  run_test(test_ascii_classes_partition_the_printables, "test_ascii_classes_partition_the_printables", 138);

  return UNITY_END();
}
