/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "anchor_cost/anchor_cost.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_anchor_header_is_self_contained(void);
extern void test_anchor_table_covers_every_byte(void);
extern void test_anchor_never_picks_the_terminator(void);
extern void test_anchor_cost_is_never_zero(void);
extern void test_anchor_prefers_rare_bytes_to_common_ones(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/anchor_cost/test_anchor_cost\\test_anchor_cost.c");
  run_test(test_anchor_header_is_self_contained, "test_anchor_header_is_self_contained", 8);
  run_test(test_anchor_table_covers_every_byte, "test_anchor_table_covers_every_byte", 13);
  run_test(test_anchor_never_picks_the_terminator, "test_anchor_never_picks_the_terminator", 18);
  run_test(test_anchor_cost_is_never_zero, "test_anchor_cost_is_never_zero", 24);
  run_test(test_anchor_prefers_rare_bytes_to_common_ones, "test_anchor_prefers_rare_bytes_to_common_ones", 32);

  return UNITY_END();
}
