/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "endian/endian.h"
#include <stdint.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_the_exact_arithmetic_this_suite_relies_on_is_itself_right(void);
extern void test_the_host_order_write_places_every_byte(void);
extern void test_the_reversed_write_places_every_byte(void);
extern void test_each_read_returns_the_value_its_bytes_stand_for(void);
extern void test_the_reversal_mirrors_every_byte_across_the_width(void);
extern void test_a_write_then_a_read_of_the_same_order_returns_the_value(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/accuracy/test_endian_accuracy\\test_endian_accuracy.c");
  run_test(test_the_exact_arithmetic_this_suite_relies_on_is_itself_right, "test_the_exact_arithmetic_this_suite_relies_on_is_itself_right", 124);
  run_test(test_the_host_order_write_places_every_byte, "test_the_host_order_write_places_every_byte", 142);
  run_test(test_the_reversed_write_places_every_byte, "test_the_reversed_write_places_every_byte", 185);
  run_test(test_each_read_returns_the_value_its_bytes_stand_for, "test_each_read_returns_the_value_its_bytes_stand_for", 227);
  run_test(test_the_reversal_mirrors_every_byte_across_the_width, "test_the_reversal_mirrors_every_byte_across_the_width", 268);
  run_test(test_a_write_then_a_read_of_the_same_order_returns_the_value, "test_a_write_then_a_read_of_the_same_order_returns_the_value", 304);

  return UNITY_END();
}
