/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "oracle_divergence.h"
#include "octetus_introitus_exitus/octetus_introitus_exitus.h"
#include "cellularum_laboro/cellularum_laboro.h"
#include "numeros_scribo/numeros_scribo.h"
#include "spatium/spatium.h"
#include "verba_scribo/verba_scribo.h"
#include "verbum_scrutor/verbum_scrutor.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_len_of_a_run_that_never_terminates(void);
extern void test_len_finds_a_terminator_in_every_lane(void);
extern void test_len_at_every_start_alignment(void);
extern void test_chr_of_a_byte_that_is_not_there_in_an_unterminated_run(void);
extern void test_chr_finds_a_byte_in_every_lane(void);
extern void test_chr_of_the_terminator_itself(void);
extern void test_a_run_of_high_bytes_measures_and_searches_like_libc(void);
extern void test_folding_never_touches_a_byte_outside_the_letters(void);
extern void test_a_case_insensitive_search_through_high_bytes(void);
extern void test_find_where_every_lane_is_a_candidate(void);
extern void test_find_a_needle_that_is_only_the_last_bytes(void);
extern void test_find_a_needle_one_byte_longer_than_the_hay(void);
extern void test_find_the_hay_in_itself(void);
extern void test_find_across_every_word_boundary(void);
extern void test_find_with_the_terminator_before_the_match(void);
extern void test_find_of_an_empty_needle(void);
extern void test_copy_never_writes_past_its_destination(void);
extern void test_copy_of_a_source_that_never_terminates(void);
extern void test_a_builder_at_every_capacity_stays_inside_it(void);
extern void test_a_builder_with_no_room_for_a_terminator(void);
extern void test_a_write_of_every_length_into_a_fixed_buffer(void);
extern void test_a_record_at_every_capacity_stays_inside_it(void);
extern void test_appending_to_a_record_until_it_stops_fitting(void);
extern void test_the_parsers_against_content_that_never_terminates(void);
extern void test_the_parsers_agree_with_libc_on_rubbish(void);
extern void test_the_parser_takes_decimal_and_stops_at_anything_else(void);
extern void test_an_exponent_with_no_digits_after_it(void);
extern void test_an_exponent_that_is_real_is_still_taken(void);
extern void test_a_number_made_entirely_of_leading_zeros(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/integration/test_hostile_content\\test_hostile_content.c");
  run_test(test_len_of_a_run_that_never_terminates, "test_len_of_a_run_that_never_terminates", 89);
  run_test(test_len_finds_a_terminator_in_every_lane, "test_len_finds_a_terminator_in_every_lane", 102);
  run_test(test_len_at_every_start_alignment, "test_len_at_every_start_alignment", 117);
  run_test(test_chr_of_a_byte_that_is_not_there_in_an_unterminated_run, "test_chr_of_a_byte_that_is_not_there_in_an_unterminated_run", 131);
  run_test(test_chr_finds_a_byte_in_every_lane, "test_chr_finds_a_byte_in_every_lane", 141);
  run_test(test_chr_of_the_terminator_itself, "test_chr_of_the_terminator_itself", 158);
  run_test(test_a_run_of_high_bytes_measures_and_searches_like_libc, "test_a_run_of_high_bytes_measures_and_searches_like_libc", 177);
  run_test(test_folding_never_touches_a_byte_outside_the_letters, "test_folding_never_touches_a_byte_outside_the_letters", 191);
  run_test(test_a_case_insensitive_search_through_high_bytes, "test_a_case_insensitive_search_through_high_bytes", 215);
  run_test(test_find_where_every_lane_is_a_candidate, "test_find_where_every_lane_is_a_candidate", 234);
  run_test(test_find_a_needle_that_is_only_the_last_bytes, "test_find_a_needle_that_is_only_the_last_bytes", 247);
  run_test(test_find_a_needle_one_byte_longer_than_the_hay, "test_find_a_needle_one_byte_longer_than_the_hay", 266);
  run_test(test_find_the_hay_in_itself, "test_find_the_hay_in_itself", 277);
  run_test(test_find_across_every_word_boundary, "test_find_across_every_word_boundary", 287);
  run_test(test_find_with_the_terminator_before_the_match, "test_find_with_the_terminator_before_the_match", 304);
  run_test(test_find_of_an_empty_needle, "test_find_of_an_empty_needle", 319);
  run_test(test_copy_never_writes_past_its_destination, "test_copy_never_writes_past_its_destination", 334);
  run_test(test_copy_of_a_source_that_never_terminates, "test_copy_of_a_source_that_never_terminates", 350);
  run_test(test_a_builder_at_every_capacity_stays_inside_it, "test_a_builder_at_every_capacity_stays_inside_it", 368);
  run_test(test_a_builder_with_no_room_for_a_terminator, "test_a_builder_with_no_room_for_a_terminator", 393);
  run_test(test_a_write_of_every_length_into_a_fixed_buffer, "test_a_write_of_every_length_into_a_fixed_buffer", 404);
  run_test(test_a_record_at_every_capacity_stays_inside_it, "test_a_record_at_every_capacity_stays_inside_it", 444);
  run_test(test_appending_to_a_record_until_it_stops_fitting, "test_appending_to_a_record_until_it_stops_fitting", 459);
  run_test(test_the_parsers_against_content_that_never_terminates, "test_the_parsers_against_content_that_never_terminates", 480);
  run_test(test_the_parsers_agree_with_libc_on_rubbish, "test_the_parsers_agree_with_libc_on_rubbish", 494);
  run_test(test_the_parser_takes_decimal_and_stops_at_anything_else, "test_the_parser_takes_decimal_and_stops_at_anything_else", 531);
  run_test(test_an_exponent_with_no_digits_after_it, "test_an_exponent_with_no_digits_after_it", 552);
  run_test(test_an_exponent_that_is_real_is_still_taken, "test_an_exponent_that_is_real_is_still_taken", 581);
  run_test(test_a_number_made_entirely_of_leading_zeros, "test_a_number_made_entirely_of_leading_zeros", 589);

  return UNITY_END();
}
