// memmanager - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
#ifndef MMGR_ASCII_MASK_H
#define MMGR_ASCII_MASK_H

#include "mmgr_config.h"

MMGR_BEGIN_DECLS

/**
 * @file ascii_mask.h
 * @brief Character classes as bitmaps. One shift and one and answers any of them.
 *
 * Every class costs the same. There is no cheap class and no expensive one, and no range chain
 * anywhere. ws() was six compares and a branch. digit() was two. Neither is now.
 *
 * Sixteen bytes, not two uint64. The obvious spelling is a pair of 64-bit halves indexed by bit 6,
 * and on x86 that is fine. This library also builds at MMGR_WORD_BITS 16, where a 64-bit shift is a
 * called routine and a 64-bit constant is four loads. Byte indexing is one load, one shift and one
 * and on every width, and needs no per-width spelling of the constants.
 *
 * Generated by tools/dev_env/gen_ascii_masks.py from the predicates. These are exactly the
 * constants nobody can check by eye - the first three written out by hand had 'Z' missing from
 * ALPHA, and space, DEL and 0x1F wrongly in PUNCT.
 *
 * Bytes at or above 0x80 are in no class.
 */

/** @brief A 128-bit character class. */
typedef struct
{
    uint8_t b[16];
} MmgrAsciiMask;

MMGR_STATIC_ASSERT(sizeof(MmgrAsciiMask) == 16u, "an ASCII class mask is exactly 128 bits");

/** @brief 0-9 */
#define MMGR_ASCII_NUM_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}

/** @brief A-Z a-z */
#define MMGR_ASCII_ALPHA_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFE, 0xFF, 0xFF, 0x07, 0xFE, 0xFF, 0xFF, 0x07}}

/** @brief 0-9 A-Z a-z */
#define MMGR_ASCII_ALNUM_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x03, 0xFE, 0xFF, 0xFF, 0x07, 0xFE, 0xFF, 0xFF, 0x07}}

/** @brief A-Z */
#define MMGR_ASCII_UPPER_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFE, 0xFF, 0xFF, 0x07, 0x00, 0x00, 0x00, 0x00}}

/** @brief a-z */
#define MMGR_ASCII_LOWER_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFE, 0xFF, 0xFF, 0x07}}

/** @brief 0-9 A-F a-f */
#define MMGR_ASCII_HEX_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x03, 0x7E, 0x00, 0x00, 0x00, 0x7E, 0x00, 0x00, 0x00}}

/** @brief printable, not alphanumeric, not space */
#define MMGR_ASCII_PUNCT_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0xFE, 0xFF, 0x00, 0xFC, 0x01, 0x00, 0x00, 0xF8, 0x01, 0x00, 0x00, 0x78}}

/** @brief space tab newline vtab formfeed return */
#define MMGR_ASCII_SPACE_INIT                                            \
    {{0x00, 0x3E, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}

/** @brief space through ~ */
#define MMGR_ASCII_PRINT_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x7F}}

/** @brief below space, and DEL */
#define MMGR_ASCII_CTRL_INIT                                            \
    {{0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80}}

/** @brief 0-9 */
static const MmgrAsciiMask mmgr_ascii_num MMGR_UNUSED = MMGR_ASCII_NUM_INIT;
/** @brief A-Z a-z */
static const MmgrAsciiMask mmgr_ascii_alpha MMGR_UNUSED = MMGR_ASCII_ALPHA_INIT;
/** @brief 0-9 A-Z a-z */
static const MmgrAsciiMask mmgr_ascii_alnum MMGR_UNUSED = MMGR_ASCII_ALNUM_INIT;
/** @brief A-Z */
static const MmgrAsciiMask mmgr_ascii_upper MMGR_UNUSED = MMGR_ASCII_UPPER_INIT;
/** @brief a-z */
static const MmgrAsciiMask mmgr_ascii_lower MMGR_UNUSED = MMGR_ASCII_LOWER_INIT;
/** @brief 0-9 A-F a-f */
static const MmgrAsciiMask mmgr_ascii_hex MMGR_UNUSED = MMGR_ASCII_HEX_INIT;
/** @brief printable, not alphanumeric, not space */
static const MmgrAsciiMask mmgr_ascii_punct MMGR_UNUSED = MMGR_ASCII_PUNCT_INIT;
/** @brief space tab newline vtab formfeed return */
static const MmgrAsciiMask mmgr_ascii_space MMGR_UNUSED = MMGR_ASCII_SPACE_INIT;
/** @brief space through ~ */
static const MmgrAsciiMask mmgr_ascii_print MMGR_UNUSED = MMGR_ASCII_PRINT_INIT;
/** @brief below space, and DEL */
static const MmgrAsciiMask mmgr_ascii_ctrl MMGR_UNUSED = MMGR_ASCII_CTRL_INIT;

/**
 * @brief Is @p c in class @p m.
 * @param m Class mask.
 * @param c Byte to test.
 * @return MMGR_TRUE if it is. Anything at or above 0x80 is never in a class.
 */
MMGR_INLINE mmgr_bool mmgr_ascii_in(const MmgrAsciiMask *m, uint8_t c)
{
    return (mmgr_bool)((c < 0x80u) && (((m->b[c >> 3] >> (c & 7u)) & 1u) != 0u));
}

MMGR_END_DECLS

#endif
