/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "custodia_secura/custodia_secura.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_secura_header_is_self_contained(void);
extern void test_secura_namespace_is_wired(void);
extern void test_init_hands_back_usable_memory(void);
extern void test_init_comes_out_of_the_pool_it_was_given(void);
extern void test_used_grows_with_what_was_taken(void);
extern void test_wipe_clears_the_region(void);
extern void test_wipe_stays_inside_what_it_was_asked_for(void);
extern void test_wipe_of_nothing_touches_nothing(void);
extern void test_release_wipes_what_it_gives_up(void);
extern void test_release_gives_the_bytes_back(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/custodia_secura/test_custodia_secura\\test_custodia_secura.c");
  run_test(test_secura_header_is_self_contained, "test_secura_header_is_self_contained", 20);
  run_test(test_secura_namespace_is_wired, "test_secura_namespace_is_wired", 25);
  run_test(test_init_hands_back_usable_memory, "test_init_hands_back_usable_memory", 34);
  run_test(test_init_comes_out_of_the_pool_it_was_given, "test_init_comes_out_of_the_pool_it_was_given", 45);
  run_test(test_used_grows_with_what_was_taken, "test_used_grows_with_what_was_taken", 53);
  run_test(test_wipe_clears_the_region, "test_wipe_clears_the_region", 63);
  run_test(test_wipe_stays_inside_what_it_was_asked_for, "test_wipe_stays_inside_what_it_was_asked_for", 80);
  run_test(test_wipe_of_nothing_touches_nothing, "test_wipe_of_nothing_touches_nothing", 99);
  run_test(test_release_wipes_what_it_gives_up, "test_release_wipes_what_it_gives_up", 110);
  run_test(test_release_gives_the_bytes_back, "test_release_gives_the_bytes_back", 127);

  return UNITY_END();
}
