/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "impensa_ancorae_acus/impensa_ancorae_acus.h"
#include <stdint.h>
#include <stdio.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_no_byte_costs_nothing(void);
extern void test_the_terminator_sits_at_the_ceiling(void);
extern void test_the_table_ranks_bytes_instead_of_scoring_them_alike(void);
extern void test_a_lookup_depends_on_its_own_byte_and_nothing_else(void);
extern void test_the_high_half_is_not_the_low_half_read_twice(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/accuracy/test_impensa_ancorae_acus_accuracy\\test_impensa_ancorae_acus_accuracy.c");
  run_test(test_no_byte_costs_nothing, "test_no_byte_costs_nothing", 96);
  run_test(test_the_terminator_sits_at_the_ceiling, "test_the_terminator_sits_at_the_ceiling", 116);
  run_test(test_the_table_ranks_bytes_instead_of_scoring_them_alike, "test_the_table_ranks_bytes_instead_of_scoring_them_alike", 133);
  run_test(test_a_lookup_depends_on_its_own_byte_and_nothing_else, "test_a_lookup_depends_on_its_own_byte_and_nothing_else", 168);
  run_test(test_the_high_half_is_not_the_low_half_read_twice, "test_the_high_half_is_not_the_low_half_read_twice", 207);

  return UNITY_END();
}
