/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "octetus_introitus_exitus/octetus_introitus_exitus.h"
#include <stdint.h>
#include <stdio.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_the_byte_arithmetic_this_suite_relies_on_is_itself_right(void);
extern void test_a_big_endian_append_lays_every_byte_where_the_reference_puts_it(void);
extern void test_a_big_endian_read_returns_the_value_its_bytes_stand_for(void);
extern void test_a_value_written_and_read_at_the_same_width_comes_back(void);
extern void test_a_raw_append_copies_its_bytes_unchanged(void);
extern void test_a_length_prefixed_read_points_at_the_run_and_advances_past_both(void);
extern void test_a_run_reaching_past_the_end_leaves_the_cursor_where_it_started(void);
extern void test_a_fixed_field_right_aligns_its_integer_and_zero_fills_ahead(void);
extern void test_an_integer_too_wide_for_the_field_is_refused_without_writing(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/accuracy/test_octetus_introitus_exitus_accuracy\\test_octetus_introitus_exitus_accuracy.c");
  run_test(test_the_byte_arithmetic_this_suite_relies_on_is_itself_right, "test_the_byte_arithmetic_this_suite_relies_on_is_itself_right", 132);
  run_test(test_a_big_endian_append_lays_every_byte_where_the_reference_puts_it, "test_a_big_endian_append_lays_every_byte_where_the_reference_puts_it", 181);
  run_test(test_a_big_endian_read_returns_the_value_its_bytes_stand_for, "test_a_big_endian_read_returns_the_value_its_bytes_stand_for", 230);
  run_test(test_a_value_written_and_read_at_the_same_width_comes_back, "test_a_value_written_and_read_at_the_same_width_comes_back", 259);
  run_test(test_a_raw_append_copies_its_bytes_unchanged, "test_a_raw_append_copies_its_bytes_unchanged", 312);
  run_test(test_a_length_prefixed_read_points_at_the_run_and_advances_past_both, "test_a_length_prefixed_read_points_at_the_run_and_advances_past_both", 358);
  run_test(test_a_run_reaching_past_the_end_leaves_the_cursor_where_it_started, "test_a_run_reaching_past_the_end_leaves_the_cursor_where_it_started", 411);
  run_test(test_a_fixed_field_right_aligns_its_integer_and_zero_fills_ahead, "test_a_fixed_field_right_aligns_its_integer_and_zero_fills_ahead", 453);
  run_test(test_an_integer_too_wide_for_the_field_is_refused_without_writing, "test_an_integer_too_wide_for_the_field_is_refused_without_writing", 498);

  return UNITY_END();
}
