/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_keepout_header_is_self_contained(void);
extern void test_a_drain_grants_the_segments_it_claimed(void);
extern void test_an_unaligned_range_covers_the_segments_it_touches(void);
extern void test_an_overlapping_claim_is_refused_and_leaves_the_holder_alone(void);
extern void test_disjoint_claims_coexist(void);
extern void test_no_more_drains_than_there_are_records(void);
extern void test_a_range_the_ring_does_not_hold_is_refused(void);
extern void test_a_spent_tessera_stops_working(void);
extern void test_a_reused_record_does_not_honour_the_old_tessera(void);
extern void test_a_tessera_nobody_issued_is_refused(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/confinium_exclusivum_infinitas/test_iteratio_infinita_keepout\\test_iteratio_infinita_keepout.c");
  run_test(test_keepout_header_is_self_contained, "test_keepout_header_is_self_contained", 73);
  run_test(test_a_drain_grants_the_segments_it_claimed, "test_a_drain_grants_the_segments_it_claimed", 78);
  run_test(test_an_unaligned_range_covers_the_segments_it_touches, "test_an_unaligned_range_covers_the_segments_it_touches", 89);
  run_test(test_an_overlapping_claim_is_refused_and_leaves_the_holder_alone, "test_an_overlapping_claim_is_refused_and_leaves_the_holder_alone", 98);
  run_test(test_disjoint_claims_coexist, "test_disjoint_claims_coexist", 112);
  run_test(test_no_more_drains_than_there_are_records, "test_no_more_drains_than_there_are_records", 129);
  run_test(test_a_range_the_ring_does_not_hold_is_refused, "test_a_range_the_ring_does_not_hold_is_refused", 144);
  run_test(test_a_spent_tessera_stops_working, "test_a_spent_tessera_stops_working", 155);
  run_test(test_a_reused_record_does_not_honour_the_old_tessera, "test_a_reused_record_does_not_honour_the_old_tessera", 169);
  run_test(test_a_tessera_nobody_issued_is_refused, "test_a_tessera_nobody_issued_is_refused", 187);

  return UNITY_END();
}
