/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cellularum_laboro/cellularum_laboro.h"
#include "verbum_scrutor/verbum_scrutor.h"
#include <stdio.h>
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_the_answer_does_not_depend_on_where_the_buffer_starts(void);
extern void test_len_matches_the_reference_at_every_length(void);
extern void test_len_stops_at_the_cap_at_every_length(void);
extern void test_chr_matches_the_reference_at_every_length(void);
extern void test_diff_matches_the_reference_at_every_length(void);
extern void test_find_matches_the_reference_at_every_needle_and_hay_length(void);
extern void test_find_matches_the_reference_with_the_match_at_every_position(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/integration/test_scan_reference\\test_scan_reference.c");
  run_test(test_the_answer_does_not_depend_on_where_the_buffer_starts, "test_the_answer_does_not_depend_on_where_the_buffer_starts", 138);
  run_test(test_len_matches_the_reference_at_every_length, "test_len_matches_the_reference_at_every_length", 186);
  run_test(test_len_stops_at_the_cap_at_every_length, "test_len_stops_at_the_cap_at_every_length", 201);
  run_test(test_chr_matches_the_reference_at_every_length, "test_chr_matches_the_reference_at_every_length", 214);
  run_test(test_diff_matches_the_reference_at_every_length, "test_diff_matches_the_reference_at_every_length", 234);
  run_test(test_find_matches_the_reference_at_every_needle_and_hay_length, "test_find_matches_the_reference_at_every_needle_and_hay_length", 258);
  run_test(test_find_matches_the_reference_with_the_match_at_every_position, "test_find_matches_the_reference_with_the_match_at_every_position", 291);

  return UNITY_END();
}
