/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cellularum_laboro/cellularum_laboro.h"
#include <stdint.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_the_exact_arithmetic_this_suite_relies_on_is_itself_right(void);
extern void test_a_signed_integer_comes_back_as_the_integer_it_names(void);
extern void test_an_unsigned_integer_comes_back_as_the_integer_it_names(void);
extern void test_a_decimal_a_double_holds_outright_comes_back_exactly(void);
extern void test_a_decimal_no_double_holds_comes_back_correctly_rounded(void);
extern void test_the_float_entry_is_the_double_entry_narrowed(void);
extern void test_a_case_insensitive_compare_holds_on_an_accented_word(void);
extern void test_a_case_insensitive_search_finds_a_word_after_an_accented_one(void);
extern void test_a_case_insensitive_compare_holds_for_every_planted_byte(void);
extern void test_a_sign_in_the_text_reaches_the_value(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/accuracy/test_cellularum_laboro_accuracy\\test_cellularum_laboro_accuracy.c");
  run_test(test_the_exact_arithmetic_this_suite_relies_on_is_itself_right, "test_the_exact_arithmetic_this_suite_relies_on_is_itself_right", 148);
  run_test(test_a_signed_integer_comes_back_as_the_integer_it_names, "test_a_signed_integer_comes_back_as_the_integer_it_names", 164);
  run_test(test_an_unsigned_integer_comes_back_as_the_integer_it_names, "test_an_unsigned_integer_comes_back_as_the_integer_it_names", 183);
  run_test(test_a_decimal_a_double_holds_outright_comes_back_exactly, "test_a_decimal_a_double_holds_outright_comes_back_exactly", 200);
  run_test(test_a_decimal_no_double_holds_comes_back_correctly_rounded, "test_a_decimal_no_double_holds_comes_back_correctly_rounded", 223);
  run_test(test_the_float_entry_is_the_double_entry_narrowed, "test_the_float_entry_is_the_double_entry_narrowed", 246);
  run_test(test_a_case_insensitive_compare_holds_on_an_accented_word, "test_a_case_insensitive_compare_holds_on_an_accented_word", 281);
  run_test(test_a_case_insensitive_search_finds_a_word_after_an_accented_one, "test_a_case_insensitive_search_finds_a_word_after_an_accented_one", 320);
  run_test(test_a_case_insensitive_compare_holds_for_every_planted_byte, "test_a_case_insensitive_compare_holds_for_every_planted_byte", 345);
  run_test(test_a_sign_in_the_text_reaches_the_value, "test_a_sign_in_the_text_reaches_the_value", 390);

  return UNITY_END();
}
