#!/usr/bin/env python3
# memmanager - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Emit src/ascii_mask/ascii_mask.h.

Bitmaps, not range chains: one shift and one and answers any class, and every class costs the same.

Sixteen bytes rather than two uint64, because this library builds at MMGR_WORD_BITS 16 as well as
64 and a 64-bit shift is a called routine there. Indexing bytes is the same one load, one shift, one
and on every width, and needs no per-width spelling of the constants.
"""

import math
import pathlib

# HERE is mmgr/tools/dev_env, LIB is mmgr. Same convention as readclean.py, so the generator runs
# from anywhere.
HERE = pathlib.Path(__file__).resolve().parent
LIB = HERE.parent.parent
OUT = LIB / "src" / "ascii_mask"
OUT.mkdir(parents=True, exist_ok=True)


def num(c):
    return 0x30 <= c <= 0x39


def upper(c):
    return 0x41 <= c <= 0x5A


def lower(c):
    return 0x61 <= c <= 0x7A


def alpha(c):
    return upper(c) or lower(c)


def alnum(c):
    return alpha(c) or num(c)


def space(c):
    return c == 0x20 or 0x09 <= c <= 0x0D


def punct(c):
    return 0x21 <= c <= 0x7E and not alnum(c)


def hexd(c):
    return num(c) or (0x41 <= c <= 0x46) or (0x61 <= c <= 0x66)


def prnt(c):
    return 0x20 <= c <= 0x7E


def ctrl(c):
    return c < 0x20 or c == 0x7F


CLASSES = [
    ("NUM", num, "0-9"),
    ("ALPHA", alpha, "A-Z a-z"),
    ("ALNUM", alnum, "0-9 A-Z a-z"),
    ("UPPER", upper, "A-Z"),
    ("LOWER", lower, "a-z"),
    ("HEX", hexd, "0-9 A-F a-f"),
    ("PUNCT", punct, "printable, not alphanumeric, not space"),
    ("SPACE", space, "space tab newline vtab formfeed return"),
    ("PRINT", prnt, "space through ~"),
    ("CTRL", ctrl, "below space, and DEL"),
]


def bytes_of(pred):
    b = [0] * 16
    for c in range(128):
        if pred(c):
            b[c >> 3] |= 1 << (c & 7)
    return b


lines = []
for name, pred, doc in CLASSES:
    b = bytes_of(pred)
    rows = ", ".join(f"0x{x:02X}" for x in b)
    lines.append(
        f"/** @\x62rief {doc} */\n#define MMGR_ASCII_{name}_INIT                                            \\\n"
        f"    {{{{{rows}}}}}"
    )

body = "\n\n".join(lines)

decls = "\n".join(
    f"/** @\x62rief {doc} */\nstatic const MmgrAsciiMask mmgr_ascii_{n.lower()} MMGR_UNUSED = MMGR_ASCII_{n}_INIT;"
    for n, _, doc in CLASSES
)

HDR = f"""// memmanager - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
#ifndef MMGR_ASCII_MASK_H
#define MMGR_ASCII_MASK_H

#include "config/mmgr_config.h"

MMGR_BEGIN_DECLS

/**
 * @file ascii_mask.h
 * @brief Character classes as bitmaps. One shift and one and answers any of them.
 *
 * Every class costs the same. There is no cheap class and no expensive one, and no range chain
 * anywhere. ws() was six compares and a branch. digit() was two. Neither is now.
 *
 * Sixteen bytes, not two uint64. The obvious spelling is a pair of 64-bit halves indexed by bit 6,
 * and on x86 that is fine. This library also builds at MMGR_WORD_BITS 16, where a 64-bit shift is a
 * called routine and a 64-bit constant is four loads. Byte indexing is one load, one shift and one
 * and on every width, and needs no per-width spelling of the constants.
 *
 * Generated by tools/dev_env/gen_ascii_masks.py from the predicates. These are exactly the
 * constants nobody can check by eye - the first three written out by hand had 'Z' missing from
 * ALPHA, and space, DEL and 0x1F wrongly in PUNCT.
 *
 * Bytes at or above 0x80 are in no class.
 */

/** @brief A 128-bit character class. */
typedef struct
{{
    uint8_t b[16];
}} MmgrAsciiMask;

MMGR_STATIC_ASSERT(sizeof(MmgrAsciiMask) == 16u, "an ASCII class mask is exactly 128 bits");

{body}

{decls}

/**
 * @brief Is @p c in class @p m.
 * @param m Class mask.
 * @param c Byte to test.
 * @return MMGR_TRUE if it is. Anything at or above 0x80 is never in a class.
 */
MMGR_INLINE mmgr_bool mmgr_ascii_in(const MmgrAsciiMask *m, uint8_t c)
{{
    return (mmgr_bool)((c < 0x80u) && (((m->b[c >> 3] >> (c & 7u)) & 1u) != 0u));
}}

MMGR_END_DECLS

#endif
"""

p = OUT / "ascii_mask.h"
p.write_text(HDR, encoding="utf-8")

(OUT / "CMakeLists.txt").write_text(
    """# memmanager - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

# No .c. The module is a set of const bitmaps and one inline that indexes them.
mmgr_add_module(ascii_mask
  HEADER_ONLY
)
""",
    encoding="utf-8",
)

print(f"wrote {p}")
for name, pred, _ in CLASSES:
    b = bytes_of(pred)
    lo = int.from_bytes(bytes(b[:8]), "little")
    hi = int.from_bytes(bytes(b[8:]), "little")
    print(f"  {name:6} low=0x{lo:016X} high=0x{hi:016X}")
