/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "config/mmgr_string_shim.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_shim_header_is_self_contained(void);
extern void test_shim_bound_is_a_compile_time_constant(void);
extern void test_shim_strlen(void);
extern void test_shim_strstr(void);
extern void test_shim_strcmp_is_equality(void);
extern void test_shim_strncmp_bounds_the_compare(void);
extern void test_shim_memory_entries(void);
extern void test_shim_memmove_handles_overlap(void);
extern void test_shim_strchr_finds_the_terminator(void);
extern void test_shim_strlcpy_reports_what_it_wrote(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/config/mmgr_string_shim/test_mmgr_string_shim\\test_mmgr_string_shim.c");
  run_test(test_shim_header_is_self_contained, "test_shim_header_is_self_contained", 5);
  run_test(test_shim_bound_is_a_compile_time_constant, "test_shim_bound_is_a_compile_time_constant", 10);
  run_test(test_shim_strlen, "test_shim_strlen", 15);
  run_test(test_shim_strstr, "test_shim_strstr", 22);
  run_test(test_shim_strcmp_is_equality, "test_shim_strcmp_is_equality", 31);
  run_test(test_shim_strncmp_bounds_the_compare, "test_shim_strncmp_bounds_the_compare", 38);
  run_test(test_shim_memory_entries, "test_shim_memory_entries", 44);
  run_test(test_shim_memmove_handles_overlap, "test_shim_memmove_handles_overlap", 56);
  run_test(test_shim_strchr_finds_the_terminator, "test_shim_strchr_finds_the_terminator", 66);
  run_test(test_shim_strlcpy_reports_what_it_wrote, "test_shim_strlcpy_reports_what_it_wrote", 74);

  return UNITY_END();
}
