/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_stream_header_is_self_contained(void);
extern void test_the_path_opens_to_one_auctor_and_stays_there(void);
extern void test_a_unit_that_is_not_one_store_is_refused(void);
extern void test_a_status_can_be_read_without_asking_for_anything(void);
extern void test_a_cfg_and_no_ask_attaches_the_path(void);
extern void test_every_count_on_the_path_is_in_units(void);
extern void test_the_head_only_ever_moves_by_whole_units(void);
extern void test_a_grant_publishes_nothing_until_it_is_committed(void);
extern void test_a_grant_never_wraps(void);
extern void test_asking_for_whatever_fits_needs_somewhere_to_be_told(void);
extern void test_one_grant_at_a_time(void);
extern void test_a_spent_tessera_publishes_nothing(void);
extern void test_a_drain_tessera_will_not_publish_an_ingest(void);
extern void test_an_ingest_tessera_will_not_open_a_drain(void);
extern void test_a_grant_and_a_drain_are_denied_by_the_same_word(void);
extern void test_a_drain_cannot_have_ground_a_grant_is_holding(void);
extern void test_only_the_auctor_may_detach(void);
extern void test_a_grant_still_out_refuses_the_detach(void);
extern void test_a_new_stream_takes_the_path_and_the_old_tokens_stop(void);
extern void test_a_bytewise_stream_survives_the_wrap(void);
extern void test_a_wordwise_stream_survives_the_wrap(void);
extern void test_a_stream_runs_while_drains_are_worked(void);
extern void test_a_wordwise_stream_runs_while_drains_are_worked(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/confinium_exclusivum_infinitas/test_singularitas_stream\\test_singularitas_stream.c");
  run_test(test_stream_header_is_self_contained, "test_stream_header_is_self_contained", 70);
  run_test(test_the_path_opens_to_one_auctor_and_stays_there, "test_the_path_opens_to_one_auctor_and_stays_there", 75);
  run_test(test_a_unit_that_is_not_one_store_is_refused, "test_a_unit_that_is_not_one_store_is_refused", 91);
  run_test(test_a_status_can_be_read_without_asking_for_anything, "test_a_status_can_be_read_without_asking_for_anything", 104);
  run_test(test_a_cfg_and_no_ask_attaches_the_path, "test_a_cfg_and_no_ask_attaches_the_path", 114);
  run_test(test_every_count_on_the_path_is_in_units, "test_every_count_on_the_path_is_in_units", 127);
  run_test(test_the_head_only_ever_moves_by_whole_units, "test_the_head_only_ever_moves_by_whole_units", 148);
  run_test(test_a_grant_publishes_nothing_until_it_is_committed, "test_a_grant_publishes_nothing_until_it_is_committed", 178);
  run_test(test_a_grant_never_wraps, "test_a_grant_never_wraps", 199);
  run_test(test_asking_for_whatever_fits_needs_somewhere_to_be_told, "test_asking_for_whatever_fits_needs_somewhere_to_be_told", 224);
  run_test(test_one_grant_at_a_time, "test_one_grant_at_a_time", 235);
  run_test(test_a_spent_tessera_publishes_nothing, "test_a_spent_tessera_publishes_nothing", 252);
  run_test(test_a_drain_tessera_will_not_publish_an_ingest, "test_a_drain_tessera_will_not_publish_an_ingest", 273);
  run_test(test_an_ingest_tessera_will_not_open_a_drain, "test_an_ingest_tessera_will_not_open_a_drain", 291);
  run_test(test_a_grant_and_a_drain_are_denied_by_the_same_word, "test_a_grant_and_a_drain_are_denied_by_the_same_word", 305);
  run_test(test_a_drain_cannot_have_ground_a_grant_is_holding, "test_a_drain_cannot_have_ground_a_grant_is_holding", 336);
  run_test(test_only_the_auctor_may_detach, "test_only_the_auctor_may_detach", 361);
  run_test(test_a_grant_still_out_refuses_the_detach, "test_a_grant_still_out_refuses_the_detach", 376);
  run_test(test_a_new_stream_takes_the_path_and_the_old_tokens_stop, "test_a_new_stream_takes_the_path_and_the_old_tokens_stop", 393);
  run_test(test_a_bytewise_stream_survives_the_wrap, "test_a_bytewise_stream_survives_the_wrap", 524);
  run_test(test_a_wordwise_stream_survives_the_wrap, "test_a_wordwise_stream_survives_the_wrap", 529);
  run_test(test_a_stream_runs_while_drains_are_worked, "test_a_stream_runs_while_drains_are_worked", 534);
  run_test(test_a_wordwise_stream_runs_while_drains_are_worked, "test_a_wordwise_stream_runs_while_drains_are_worked", 539);

  return UNITY_END();
}
