/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "memoria_externa/memoria_externa.h"
#include <stdint.h>
#include <stdio.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_the_reference_policy_this_suite_relies_on_is_itself_right(void);
extern void test_every_placement_decision_matches_the_documented_policy(void);
extern void test_a_request_larger_than_the_free_bytes_is_refused_at_the_top_of_the_range(void);
extern void test_the_two_buffer_indexes_are_always_each_others_complement(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/accuracy/test_memoria_externa_accuracy\\test_memoria_externa_accuracy.c");
  run_test(test_the_reference_policy_this_suite_relies_on_is_itself_right, "test_the_reference_policy_this_suite_relies_on_is_itself_right", 147);
  run_test(test_every_placement_decision_matches_the_documented_policy, "test_every_placement_decision_matches_the_documented_policy", 179);
  run_test(test_a_request_larger_than_the_free_bytes_is_refused_at_the_top_of_the_range, "test_a_request_larger_than_the_free_bytes_is_refused_at_the_top_of_the_range", 234);
  run_test(test_the_two_buffer_indexes_are_always_each_others_complement, "test_the_two_buffer_indexes_are_always_each_others_complement", 265);

  return UNITY_END();
}
