/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "bitio/bitio.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_bitio_header_is_self_contained(void);
extern void test_a_whole_byte_lands_as_that_byte(void);
extern void test_bits_pack_from_the_low_end(void);
extern void test_a_partial_write_waits_for_the_byte(void);
extern void test_align_flushes_the_partial_byte(void);
extern void test_align_on_a_boundary_writes_nothing(void);
extern void test_align_on_an_empty_writer_writes_nothing(void);
extern void test_a_wide_put_spans_bytes(void);
extern void test_n_at_or_above_32_takes_the_value_whole(void);
extern void test_a_narrow_put_ignores_the_high_bits(void);
extern void test_overflow_latches_and_stops_writing(void);
extern void test_a_put_after_overflow_is_ignored(void);
extern void test_align_overflows_when_there_is_no_room(void);
extern void test_namespace_is_wired(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/bitio/test_bitio\\test_bitio.c");
  run_test(test_bitio_header_is_self_contained, "test_bitio_header_is_self_contained", 29);
  run_test(test_a_whole_byte_lands_as_that_byte, "test_a_whole_byte_lands_as_that_byte", 34);
  run_test(test_bits_pack_from_the_low_end, "test_bits_pack_from_the_low_end", 42);
  run_test(test_a_partial_write_waits_for_the_byte, "test_a_partial_write_waits_for_the_byte", 53);
  run_test(test_align_flushes_the_partial_byte, "test_align_flushes_the_partial_byte", 61);
  run_test(test_align_on_a_boundary_writes_nothing, "test_align_on_a_boundary_writes_nothing", 70);
  run_test(test_align_on_an_empty_writer_writes_nothing, "test_align_on_an_empty_writer_writes_nothing", 78);
  run_test(test_a_wide_put_spans_bytes, "test_a_wide_put_spans_bytes", 85);
  run_test(test_n_at_or_above_32_takes_the_value_whole, "test_n_at_or_above_32_takes_the_value_whole", 95);
  run_test(test_a_narrow_put_ignores_the_high_bits, "test_a_narrow_put_ignores_the_high_bits", 106);
  run_test(test_overflow_latches_and_stops_writing, "test_overflow_latches_and_stops_writing", 113);
  run_test(test_a_put_after_overflow_is_ignored, "test_a_put_after_overflow_is_ignored", 127);
  run_test(test_align_overflows_when_there_is_no_room, "test_align_overflows_when_there_is_no_room", 139);
  run_test(test_namespace_is_wired, "test_namespace_is_wired", 149);

  return UNITY_END();
}
