/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "spatium/spatium.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_spatium_header_is_self_contained(void);
extern void test_the_namespace_is_wired(void);
extern void test_a_span_covers_the_buffer_it_was_given(void);
extern void test_a_read_span_covers_the_buffer_it_was_given(void);
extern void test_a_span_with_no_storage_is_not_ok(void);
extern void test_a_narrowing_past_the_end_fails_rather_than_shortening(void);
extern void test_a_narrowing_keeps_the_bytes_it_names(void);
extern void test_a_narrowing_carries_the_cursor(void);
extern void test_reset_clears_the_sticky_overflow(void);
extern void test_a_read_span_reports_what_was_written(void);
extern void test_a_read_span_carries_the_fill_spans_failure(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/spatium/test_spatium\\test_spatium.c");
  run_test(test_spatium_header_is_self_contained, "test_spatium_header_is_self_contained", 19);
  run_test(test_the_namespace_is_wired, "test_the_namespace_is_wired", 24);
  run_test(test_a_span_covers_the_buffer_it_was_given, "test_a_span_covers_the_buffer_it_was_given", 31);
  run_test(test_a_read_span_covers_the_buffer_it_was_given, "test_a_read_span_covers_the_buffer_it_was_given", 43);
  run_test(test_a_span_with_no_storage_is_not_ok, "test_a_span_with_no_storage_is_not_ok", 53);
  run_test(test_a_narrowing_past_the_end_fails_rather_than_shortening, "test_a_narrowing_past_the_end_fails_rather_than_shortening", 72);
  run_test(test_a_narrowing_keeps_the_bytes_it_names, "test_a_narrowing_keeps_the_bytes_it_names", 86);
  run_test(test_a_narrowing_carries_the_cursor, "test_a_narrowing_carries_the_cursor", 100);
  run_test(test_reset_clears_the_sticky_overflow, "test_reset_clears_the_sticky_overflow", 111);
  run_test(test_a_read_span_reports_what_was_written, "test_a_read_span_reports_what_was_written", 125);
  run_test(test_a_read_span_carries_the_fill_spans_failure, "test_a_read_span_carries_the_fill_spans_failure", 143);

  return UNITY_END();
}
