// memmanager - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Generated by tools/dev_env/gen_ancorae_formae.py. Editing this by hand is undone the next time
// anyone runs the generator, and `harness.py generated` will say so before that happens.
#include "impensa_ancorae_acus/impensa_ancorae_acus.h"

/**
 * @file impensa_ancorae_acus_english.c
 *
 * English prose. Monogram frequencies from 4.5e9 characters of Wortschatz text
 * (practicalcryptography.com); space taken at twice E per Wikipedia's letter frequency page.
 *
 * Cost is how common a byte is, so the picker takes the minimum. A byte that cannot occur under
 * this profile scores best, because a needle containing one is filtered on the first row.
 *
 * Generated, not hand tuned. See tools/dev_env/gen_ancorae_formae.py.
 *
 * The table is file local. This translation unit is the only thing that can name it, and the build
 * compiles this file only when the english profile is the one selected.
 *
 * No context. The entry is an array subscript and its argument is the index.
 */

/** @brief Cost per byte value. Lower is rarer, so lower is a better anchor. NUL is pinned worst. */
static const uint8_t s_impensa[256] = {
    255,   1,   1,   1,   1,   1,   1,   1,   1, 134, 191,   1,   1, 145,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
    255, 100, 145,   1,   1,   1,   1, 158, 117, 117,   1,   1, 177, 145, 180, 127,
    145, 145, 145, 145, 145, 145, 145, 145, 145, 145, 122, 108,   1,   1,   1, 104,
      1, 146, 104, 121, 126, 155, 112, 111, 133, 142,  54,  87, 128, 116, 142, 143,
    111,  34, 139, 140, 147, 117,  94, 107,  50, 106,  37,   1,   1,   1,   1, 100,
      1, 222, 180, 197, 202, 231, 187, 186, 208, 218, 130, 162, 204, 191, 217, 218,
    186, 110, 214, 216, 223, 193, 169, 183, 126, 181, 112,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1
};

uint8_t mmgr_ancorae_impensa(uint8_t b)
{
    return s_impensa[b];
}
