// memmanager - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Generated by tools/dev_env/gen_ancorae_formae.py. Editing this by hand is undone the next time
// anyone runs the generator, and `harness.py generated` will say so before that happens.
#include "impensa_ancorae_acus/impensa_ancorae_acus.h"

/**
 * @file impensa_ancorae_acus_inet.c
 *
 * IPv6 text form and dotted quad, RFC 4291. The alphabet is 0-9 a-f A-F : . / % [ ] and
 * nothing else, so any needle byte outside it is the most selective anchor there is.
 *
 * Cost is how common a byte is, so the picker takes the minimum. A byte that cannot occur under
 * this profile scores best, because a needle containing one is filtered on the first row.
 *
 * Generated, not hand tuned. See tools/dev_env/gen_ancorae_formae.py.
 *
 * The table is file local. This translation unit is the only thing that can name it, and the build
 * compiles this file only when the inet profile is the one selected.
 *
 * No context. The entry is an array subscript and its argument is the index.
 */

/** @brief Cost per byte value. Lower is rarer, so lower is a better anchor. NUL is pinned worst. */
static const uint8_t s_impensa[256] = {
    255,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1, 137,   1,   1,   1,   1,   1,   1,   1,   1, 242, 178,
    240, 235, 231, 228, 228, 228, 228, 228, 228, 228, 255,   1,   1,   1,   1,   1,
      1, 178, 178, 178, 178, 178, 178,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1, 160,   1, 160,   1,   1,
      1, 206, 206, 206, 206, 206, 206,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1
};

/**
 * @brief What @p b costs as an anchor.
 * @param b The byte.
 * @return Its cost. Lower is rarer, so lower is a better anchor. NUL is pinned worst.
 *
 * No context. One byte in, one answer out - a struct to carry it would be a store and a load to
 * reach what was already in a register, and the entry is an array subscript whose argument is the
 * index.
 */
MMGR_INLINE uint8_t ancorae_impensa(uint8_t b)
{
    return s_impensa[b];
}

/* The namespace is a table of function pointers with the caller's argument lists in their types,
   so this is what it points at. It hands the argument to the body above.

   It is nameable rather than file local because a static const table in the header has to be able
   to point at it, and a static const table is what gcc devirtualizes. Through an extern one every
   call from another translation unit is a load of the table, a load of the entry, and an indirect
   call it cannot see through. */

uint8_t mmgr_ancorae_impensa(uint8_t b)
{
    return ancorae_impensa(b);
}
