/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "ascii_persona_bitorum/ascii_persona_bitorum.h"
#include <stdint.h>
#include <stdio.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_the_code_points_this_suite_tests_with_are_the_characters_the_header_names(void);
extern void test_every_class_holds_exactly_the_code_points_its_declaration_names(void);
extern void test_no_byte_at_or_above_the_ascii_limit_belongs_to_any_class(void);
extern void test_each_class_holds_the_number_of_code_points_its_runs_add_up_to(void);
extern void test_the_byte_on_each_side_of_every_run_falls_on_the_right_side_of_it(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/accuracy/test_ascii_persona_bitorum_accuracy\\test_ascii_persona_bitorum_accuracy.c");
  run_test(test_the_code_points_this_suite_tests_with_are_the_characters_the_header_names, "test_the_code_points_this_suite_tests_with_are_the_characters_the_header_names", 207);
  run_test(test_every_class_holds_exactly_the_code_points_its_declaration_names, "test_every_class_holds_exactly_the_code_points_its_declaration_names", 236);
  run_test(test_no_byte_at_or_above_the_ascii_limit_belongs_to_any_class, "test_no_byte_at_or_above_the_ascii_limit_belongs_to_any_class", 261);
  run_test(test_each_class_holds_the_number_of_code_points_its_runs_add_up_to, "test_each_class_holds_the_number_of_code_points_its_runs_add_up_to", 285);
  run_test(test_the_byte_on_each_side_of_every_run_falls_on_the_right_side_of_it, "test_the_byte_on_each_side_of_every_run_falls_on_the_right_side_of_it", 318);

  return UNITY_END();
}
