/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "oracle_divergence.h"
#include "cellularum_laboro/cellularum_laboro.h"
#include "verbum_scrutor/verbum_scrutor.h"
#include <ctype.h>
#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_len_stops_at_nul_and_at_cap(void);
extern void test_find_empty_needle_matches_at_zero(void);
extern void test_find_at_every_offset(void);
extern void test_find_spans_a_word_boundary(void);
extern void test_find_needle_longer_than_one_word(void);
extern void test_find_needle_lengths_one_through_nine(void);
extern void test_find_prefers_the_first_of_several_matches(void);
extern void test_find_near_miss_shares_a_prefix(void);
extern void test_find_absent(void);
extern void test_find_ci_folds_only_letters(void);
extern void test_has_agrees_with_find(void);
extern void test_eq_both_cases(void);
extern void test_starts_both_cases(void);
extern void test_diff_returns_the_first_differing_offset(void);
extern void test_diff_crossing_a_word_boundary(void);
extern void test_copy_truncates_and_terminates(void);
extern void test_classifiers(void);
extern void test_to_long_matches_strtol(void);
extern void test_to_ulong_matches_strtoul(void);
extern void test_to_long_without_an_end_pointer(void);
extern void test_to_double_matches_strtod(void);
extern void test_to_double_handles_an_exponent(void);
extern void test_to_float_matches_to_double(void);
extern void test_to_double_without_an_end_pointer(void);
extern void test_step_word_keeps_going_while_equal(void);
extern void test_step_word_stops_on_a_difference(void);
extern void test_step_word_stops_at_the_terminator(void);
extern void test_step_word_folds_case(void);
extern void test_step_byte_covers_the_same_three_verdicts(void);
extern void test_chr_matches_strchr(void);
extern void test_chr_at_every_alignment(void);
extern void test_chr_respects_the_cap(void);
extern void test_find_matches_strstr_over_a_corpus(void);
extern void test_find_ci_matches_a_folded_search(void);
extern void test_find_needle_longer_than_the_haystack(void);
extern void test_diff_matches_a_byte_loop(void);
extern void test_copy_of_an_empty_destination(void);
extern void test_ws_and_digit_agree_with_ctype(void);
extern void test_step_word_ignoring_case_agrees_on_a_folded_word(void);
extern void test_step_word_ignoring_case_still_sees_a_real_difference(void);
extern void test_step_word_ignoring_case_ends_before_a_difference(void);
extern void test_step_word_ignoring_case_ends_in_the_same_lane_as_a_difference(void);
extern void test_step_word_matching_case_ends_before_a_difference(void);
extern void test_step_word_matching_case_ends_in_the_same_lane_as_a_difference(void);
extern void test_step_word_of_a_difference_that_beats_the_end(void);
extern void test_step_word_of_two_words_that_both_run_on(void);
extern void test_step_byte_over_both_foldings_and_both_endings(void);
extern void test_diff_finds_the_first_differing_byte(void);
extern void test_diff_of_runs_that_agree_is_the_whole_run(void);
extern void test_diff_past_the_first_word(void);
extern void test_diff_ignoring_case(void);
extern void test_to_double_takes_a_leading_plus(void);
extern void test_to_double_takes_a_signed_exponent(void);
extern void test_to_double_clamps_an_absurd_exponent(void);
extern void test_to_double_of_a_negative_absurd_exponent(void);
extern void test_to_float_narrows_what_to_double_parses(void);
extern void test_starts_when_the_read_cap_ends_first(void);
extern void test_eq_when_the_read_cap_ends_first(void);
extern void test_starts_finds_a_difference_with_no_terminator_in_the_word(void);
extern void test_a_power_of_ten_past_what_is_exactly_a_double(void);
extern void test_the_reciprocal_table_carries_the_negative_exponents(void);
extern void test_every_step_of_the_table_gets_used(void);
extern void test_the_subnormals(void);
extern void test_underflow_and_overflow(void);
extern void test_more_digits_than_the_mantissa_can_hold(void);
extern void test_a_rounding_that_carries_out_of_the_mantissa(void);
extern void test_the_leading_zero_count_at_every_width(void);
extern void test_the_conversion_over_random_bit_patterns(void);
extern void test_the_conversion_over_strobed_bits(void);
extern void test_the_ends_of_the_range_through_the_table(void);
extern void test_a_subnormal_that_rounds_up_into_the_normals(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/cellularum_laboro/test_cellularum_laboro\\test_cellularum_laboro.c");
  run_test(test_len_stops_at_nul_and_at_cap, "test_len_stops_at_nul_and_at_cap", 33);
  run_test(test_find_empty_needle_matches_at_zero, "test_find_empty_needle_matches_at_zero", 40);
  run_test(test_find_at_every_offset, "test_find_at_every_offset", 46);
  run_test(test_find_spans_a_word_boundary, "test_find_spans_a_word_boundary", 56);
  run_test(test_find_needle_longer_than_one_word, "test_find_needle_longer_than_one_word", 64);
  run_test(test_find_needle_lengths_one_through_nine, "test_find_needle_lengths_one_through_nine", 72);
  run_test(test_find_prefers_the_first_of_several_matches, "test_find_prefers_the_first_of_several_matches", 83);
  run_test(test_find_near_miss_shares_a_prefix, "test_find_near_miss_shares_a_prefix", 88);
  run_test(test_find_absent, "test_find_absent", 94);
  run_test(test_find_ci_folds_only_letters, "test_find_ci_folds_only_letters", 100);
  run_test(test_has_agrees_with_find, "test_has_agrees_with_find", 107);
  run_test(test_eq_both_cases, "test_eq_both_cases", 117);
  run_test(test_starts_both_cases, "test_starts_both_cases", 131);
  run_test(test_diff_returns_the_first_differing_offset, "test_diff_returns_the_first_differing_offset", 143);
  run_test(test_diff_crossing_a_word_boundary, "test_diff_crossing_a_word_boundary", 153);
  run_test(test_copy_truncates_and_terminates, "test_copy_truncates_and_terminates", 159);
  run_test(test_classifiers, "test_classifiers", 169);
  run_test(test_to_long_matches_strtol, "test_to_long_matches_strtol", 208);
  run_test(test_to_ulong_matches_strtoul, "test_to_ulong_matches_strtoul", 230);
  run_test(test_to_long_without_an_end_pointer, "test_to_long_without_an_end_pointer", 252);
  run_test(test_to_double_matches_strtod, "test_to_double_matches_strtod", 259);
  run_test(test_to_double_handles_an_exponent, "test_to_double_handles_an_exponent", 279);
  run_test(test_to_float_matches_to_double, "test_to_float_matches_to_double", 299);
  run_test(test_to_double_without_an_end_pointer, "test_to_double_without_an_end_pointer", 311);
  run_test(test_step_word_keeps_going_while_equal, "test_step_word_keeps_going_while_equal", 322);
  run_test(test_step_word_stops_on_a_difference, "test_step_word_stops_on_a_difference", 331);
  run_test(test_step_word_stops_at_the_terminator, "test_step_word_stops_at_the_terminator", 340);
  run_test(test_step_word_folds_case, "test_step_word_folds_case", 354);
  run_test(test_step_byte_covers_the_same_three_verdicts, "test_step_byte_covers_the_same_three_verdicts", 366);
  run_test(test_chr_matches_strchr, "test_chr_matches_strchr", 393);
  run_test(test_chr_at_every_alignment, "test_chr_at_every_alignment", 412);
  run_test(test_chr_respects_the_cap, "test_chr_respects_the_cap", 427);
  run_test(test_find_matches_strstr_over_a_corpus, "test_find_matches_strstr_over_a_corpus", 436);
  run_test(test_find_ci_matches_a_folded_search, "test_find_ci_matches_a_folded_search", 465);
  run_test(test_find_needle_longer_than_the_haystack, "test_find_needle_longer_than_the_haystack", 502);
  run_test(test_diff_matches_a_byte_loop, "test_diff_matches_a_byte_loop", 510);
  run_test(test_copy_of_an_empty_destination, "test_copy_of_an_empty_destination", 536);
  run_test(test_ws_and_digit_agree_with_ctype, "test_ws_and_digit_agree_with_ctype", 542);
  run_test(test_step_word_ignoring_case_agrees_on_a_folded_word, "test_step_word_ignoring_case_agrees_on_a_folded_word", 555);
  run_test(test_step_word_ignoring_case_still_sees_a_real_difference, "test_step_word_ignoring_case_still_sees_a_real_difference", 564);
  run_test(test_step_word_ignoring_case_ends_before_a_difference, "test_step_word_ignoring_case_ends_before_a_difference", 577);
  run_test(test_step_word_ignoring_case_ends_in_the_same_lane_as_a_difference, "test_step_word_ignoring_case_ends_in_the_same_lane_as_a_difference", 589);
  run_test(test_step_word_matching_case_ends_before_a_difference, "test_step_word_matching_case_ends_before_a_difference", 601);
  run_test(test_step_word_matching_case_ends_in_the_same_lane_as_a_difference, "test_step_word_matching_case_ends_in_the_same_lane_as_a_difference", 611);
  run_test(test_step_word_of_a_difference_that_beats_the_end, "test_step_word_of_a_difference_that_beats_the_end", 621);
  run_test(test_step_word_of_two_words_that_both_run_on, "test_step_word_of_two_words_that_both_run_on", 631);
  run_test(test_step_byte_over_both_foldings_and_both_endings, "test_step_byte_over_both_foldings_and_both_endings", 641);
  run_test(test_diff_finds_the_first_differing_byte, "test_diff_finds_the_first_differing_byte", 673);
  run_test(test_diff_of_runs_that_agree_is_the_whole_run, "test_diff_of_runs_that_agree_is_the_whole_run", 683);
  run_test(test_diff_past_the_first_word, "test_diff_past_the_first_word", 692);
  run_test(test_diff_ignoring_case, "test_diff_ignoring_case", 705);
  run_test(test_to_double_takes_a_leading_plus, "test_to_double_takes_a_leading_plus", 713);
  run_test(test_to_double_takes_a_signed_exponent, "test_to_double_takes_a_signed_exponent", 720);
  run_test(test_to_double_clamps_an_absurd_exponent, "test_to_double_clamps_an_absurd_exponent", 730);
  run_test(test_to_double_of_a_negative_absurd_exponent, "test_to_double_of_a_negative_absurd_exponent", 740);
  run_test(test_to_float_narrows_what_to_double_parses, "test_to_float_narrows_what_to_double_parses", 746);
  run_test(test_starts_when_the_read_cap_ends_first, "test_starts_when_the_read_cap_ends_first", 754);
  run_test(test_eq_when_the_read_cap_ends_first, "test_eq_when_the_read_cap_ends_first", 767);
  run_test(test_starts_finds_a_difference_with_no_terminator_in_the_word, "test_starts_finds_a_difference_with_no_terminator_in_the_word", 781);
  run_test(test_a_power_of_ten_past_what_is_exactly_a_double, "test_a_power_of_ten_past_what_is_exactly_a_double", 813);
  run_test(test_the_reciprocal_table_carries_the_negative_exponents, "test_the_reciprocal_table_carries_the_negative_exponents", 822);
  run_test(test_every_step_of_the_table_gets_used, "test_every_step_of_the_table_gets_used", 832);
  run_test(test_the_subnormals, "test_the_subnormals", 848);
  run_test(test_underflow_and_overflow, "test_underflow_and_overflow", 857);
  run_test(test_more_digits_than_the_mantissa_can_hold, "test_more_digits_than_the_mantissa_can_hold", 876);
  run_test(test_a_rounding_that_carries_out_of_the_mantissa, "test_a_rounding_that_carries_out_of_the_mantissa", 884);
  run_test(test_the_leading_zero_count_at_every_width, "test_the_leading_zero_count_at_every_width", 891);
  run_test(test_the_conversion_over_random_bit_patterns, "test_the_conversion_over_random_bit_patterns", 903);
  run_test(test_the_conversion_over_strobed_bits, "test_the_conversion_over_strobed_bits", 933);
  run_test(test_the_ends_of_the_range_through_the_table, "test_the_ends_of_the_range_through_the_table", 971);
  run_test(test_a_subnormal_that_rounds_up_into_the_normals, "test_a_subnormal_that_rounds_up_into_the_normals", 988);

  return UNITY_END();
}
