/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "octetus_introitus_exitus/octetus_introitus_exitus.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_byteio_header_is_self_contained(void);
extern void test_byteio_namespace_is_wired(void);
extern void test_put_writes_one_byte(void);
extern void test_put_be_writes_the_high_byte_first(void);
extern void test_put_be_at_every_width(void);
extern void test_put_be_keeps_only_the_low_bytes(void);
extern void test_raw_copies_a_run(void);
extern void test_raw_of_nothing_does_not_latch(void);
extern void test_take_be_reads_what_put_be_wrote(void);
extern void test_take_be_walks_forward(void);
extern void test_take_be_of_nothing_succeeds(void);
extern void test_rd_u32_reads_and_advances(void);
extern void test_rd_str_reads_a_length_prefixed_run(void);
extern void test_rd_str_reads_an_empty_run(void);
extern void test_rd_str_rewinds_when_the_run_is_cut_short(void);
extern void test_rd_str_refuses_a_missing_length(void);
extern void test_rd_str_refuses_a_cursor_already_past_the_end(void);
extern void test_mpint_fixed_right_aligns_and_pads(void);
extern void test_mpint_fixed_drops_the_sign_padding(void);
extern void test_mpint_fixed_of_an_exact_width(void);
extern void test_mpint_fixed_of_zero_is_all_zero(void);
extern void test_mpint_fixed_refuses_a_value_too_wide(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/octetus_introitus_exitus/test_octetus_introitus_exitus\\test_octetus_introitus_exitus.c");
  run_test(test_byteio_header_is_self_contained, "test_byteio_header_is_self_contained", 8);
  run_test(test_byteio_namespace_is_wired, "test_byteio_namespace_is_wired", 13);
  run_test(test_put_writes_one_byte, "test_put_writes_one_byte", 28);
  run_test(test_put_be_writes_the_high_byte_first, "test_put_be_writes_the_high_byte_first", 38);
  run_test(test_put_be_at_every_width, "test_put_be_at_every_width", 51);
  run_test(test_put_be_keeps_only_the_low_bytes, "test_put_be_keeps_only_the_low_bytes", 68);
  run_test(test_raw_copies_a_run, "test_raw_copies_a_run", 79);
  run_test(test_raw_of_nothing_does_not_latch, "test_raw_of_nothing_does_not_latch", 90);
  run_test(test_take_be_reads_what_put_be_wrote, "test_take_be_reads_what_put_be_wrote", 104);
  run_test(test_take_be_walks_forward, "test_take_be_walks_forward", 116);
  run_test(test_take_be_of_nothing_succeeds, "test_take_be_of_nothing_succeeds", 131);
  run_test(test_rd_u32_reads_and_advances, "test_rd_u32_reads_and_advances", 143);
  run_test(test_rd_str_reads_a_length_prefixed_run, "test_rd_str_reads_a_length_prefixed_run", 158);
  run_test(test_rd_str_reads_an_empty_run, "test_rd_str_reads_an_empty_run", 171);
  run_test(test_rd_str_rewinds_when_the_run_is_cut_short, "test_rd_str_rewinds_when_the_run_is_cut_short", 183);
  run_test(test_rd_str_refuses_a_missing_length, "test_rd_str_refuses_a_missing_length", 194);
  run_test(test_rd_str_refuses_a_cursor_already_past_the_end, "test_rd_str_refuses_a_cursor_already_past_the_end", 205);
  run_test(test_mpint_fixed_right_aligns_and_pads, "test_mpint_fixed_right_aligns_and_pads", 225);
  run_test(test_mpint_fixed_drops_the_sign_padding, "test_mpint_fixed_drops_the_sign_padding", 237);
  run_test(test_mpint_fixed_of_an_exact_width, "test_mpint_fixed_of_an_exact_width", 248);
  run_test(test_mpint_fixed_of_zero_is_all_zero, "test_mpint_fixed_of_zero_is_all_zero", 258);
  run_test(test_mpint_fixed_refuses_a_value_too_wide, "test_mpint_fixed_refuses_a_value_too_wide", 270);

  return UNITY_END();
}
