/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "octetus_introitus_exitus/octetus_introitus_exitus.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_byteio_header_is_self_contained(void);
extern void test_byteio_namespace_is_wired(void);
extern void test_put_writes_one_byte(void);
extern void test_put_writes_the_high_byte_first(void);
extern void test_put_at_every_width(void);
extern void test_put_keeps_only_the_low_bytes(void);
extern void test_take_reads_what_put_wrote(void);
extern void test_take_reads_back_at_every_width(void);
extern void test_take_of_fewer_bytes_takes_the_leading_ones(void);
extern void test_take_reads_a_pattern_it_did_not_write(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/octetus_introitus_exitus/test_octetus_introitus_exitus\\test_octetus_introitus_exitus.c");
  run_test(test_byteio_header_is_self_contained, "test_byteio_header_is_self_contained", 5);
  run_test(test_byteio_namespace_is_wired, "test_byteio_namespace_is_wired", 10);
  run_test(test_put_writes_one_byte, "test_put_writes_one_byte", 18);
  run_test(test_put_writes_the_high_byte_first, "test_put_writes_the_high_byte_first", 28);
  run_test(test_put_at_every_width, "test_put_at_every_width", 41);
  run_test(test_put_keeps_only_the_low_bytes, "test_put_keeps_only_the_low_bytes", 57);
  run_test(test_take_reads_what_put_wrote, "test_take_reads_what_put_wrote", 68);
  run_test(test_take_reads_back_at_every_width, "test_take_reads_back_at_every_width", 79);
  run_test(test_take_of_fewer_bytes_takes_the_leading_ones, "test_take_of_fewer_bytes_takes_the_leading_ones", 102);
  run_test(test_take_reads_a_pattern_it_did_not_write, "test_take_reads_a_pattern_it_did_not_write", 113);

  return UNITY_END();
}
