/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "config/mmgr_config.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_config_header_is_self_contained(void);
extern void test_word_width_is_one_of_three(void);
extern void test_scan_width_is_the_word_width(void);
extern void test_index_never_exceeds_the_word(void);
extern void test_tenant_bound_is_a_real_size(void);
extern void test_ghost_slot_sits_past_the_workers(void);
extern void test_context_id_is_needed_exactly_when_it_is_used(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/config/mmgr_config/test_mmgr_config\\test_mmgr_config.c");
  run_test(test_config_header_is_self_contained, "test_config_header_is_self_contained", 8);
  run_test(test_word_width_is_one_of_three, "test_word_width_is_one_of_three", 13);
  run_test(test_scan_width_is_the_word_width, "test_scan_width_is_the_word_width", 19);
  run_test(test_index_never_exceeds_the_word, "test_index_never_exceeds_the_word", 25);
  run_test(test_tenant_bound_is_a_real_size, "test_tenant_bound_is_a_real_size", 30);
  run_test(test_ghost_slot_sits_past_the_workers, "test_ghost_slot_sits_past_the_workers", 38);
  run_test(test_context_id_is_needed_exactly_when_it_is_used, "test_context_id_is_needed_exactly_when_it_is_used", 43);

  return UNITY_END();
}
