/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "custodia_soluta/custodia_soluta.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_soluta_header_is_self_contained(void);
extern void test_soluta_namespace_is_wired(void);
extern void test_init_hands_back_usable_memory(void);
extern void test_init_comes_out_of_the_pool_it_was_given(void);
extern void test_used_grows_with_what_was_taken(void);
extern void test_release_gives_the_bytes_back(void);
extern void test_release_does_not_wipe(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/custodia_soluta/test_custodia_soluta\\test_custodia_soluta.c");
  run_test(test_soluta_header_is_self_contained, "test_soluta_header_is_self_contained", 25);
  run_test(test_soluta_namespace_is_wired, "test_soluta_namespace_is_wired", 30);
  run_test(test_init_hands_back_usable_memory, "test_init_hands_back_usable_memory", 39);
  run_test(test_init_comes_out_of_the_pool_it_was_given, "test_init_comes_out_of_the_pool_it_was_given", 50);
  run_test(test_used_grows_with_what_was_taken, "test_used_grows_with_what_was_taken", 58);
  run_test(test_release_gives_the_bytes_back, "test_release_gives_the_bytes_back", 69);
  run_test(test_release_does_not_wipe, "test_release_does_not_wipe", 80);

  return UNITY_END();
}
