// memmanager - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Generated by tools/dev_env/gen_ascii_persona_bitorum.py. Editing this by hand is undone the next
// time anyone runs the generator, and `harness.py generated` will say so before that happens.
#include "ascii_persona_bitorum/ascii_persona_bitorum.h"

/**
 * @file ascii_persona_bitorum.c
 * @brief The class masks, and the one question asked of them.
 *
 * The masks are here and nowhere else, and so are the macros that spell them. This is the only
 * translation unit that holds them and the only one that can name them, which is what makes the
 * header's claim true: a module that wants to know whether a byte is a digit includes a
 * declaration and gets no copy of the answer and no ten new names it has to avoid.
 *
 * A macro is not storage, so the ten that used to sit in the header cost no bytes. They cost the
 * global preprocessor namespace of every translation unit downstream of the header, which is every
 * consumer of the library, for the benefit of this one file.
 */

/** @brief 0-9 */
#define MMGR_ASCII_NUM_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}

/** @brief A-Z a-z */
#define MMGR_ASCII_ALPHA_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFE, 0xFF, 0xFF, 0x07, 0xFE, 0xFF, 0xFF, 0x07}}

/** @brief 0-9 A-Z a-z */
#define MMGR_ASCII_ALNUM_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x03, 0xFE, 0xFF, 0xFF, 0x07, 0xFE, 0xFF, 0xFF, 0x07}}

/** @brief A-Z */
#define MMGR_ASCII_UPPER_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFE, 0xFF, 0xFF, 0x07, 0x00, 0x00, 0x00, 0x00}}

/** @brief a-z */
#define MMGR_ASCII_LOWER_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFE, 0xFF, 0xFF, 0x07}}

/** @brief 0-9 A-F a-f */
#define MMGR_ASCII_HEX_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x03, 0x7E, 0x00, 0x00, 0x00, 0x7E, 0x00, 0x00, 0x00}}

/** @brief printable, not alphanumeric, not space */
#define MMGR_ASCII_PUNCT_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0xFE, 0xFF, 0x00, 0xFC, 0x01, 0x00, 0x00, 0xF8, 0x01, 0x00, 0x00, 0x78}}

/** @brief space tab newline vtab formfeed return */
#define MMGR_ASCII_SPACE_INIT                                            \
    {{0x00, 0x3E, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}

/** @brief below space, and DEL */
#define MMGR_ASCII_CTRL_INIT                                            \
    {{0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80}}

/** @brief space through ~ */
#define MMGR_ASCII_PRINT_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x7F}}

/** @brief The classes, in the order MmgrAsciiClass names them. */
static const MmgrAsciiMask s_class[MMGR_ASCII_CLASSES] = {
    [MMGR_ASCII_NUM] = MMGR_ASCII_NUM_INIT,
    [MMGR_ASCII_ALPHA] = MMGR_ASCII_ALPHA_INIT,
    [MMGR_ASCII_ALNUM] = MMGR_ASCII_ALNUM_INIT,
    [MMGR_ASCII_UPPER] = MMGR_ASCII_UPPER_INIT,
    [MMGR_ASCII_LOWER] = MMGR_ASCII_LOWER_INIT,
    [MMGR_ASCII_HEX] = MMGR_ASCII_HEX_INIT,
    [MMGR_ASCII_PUNCT] = MMGR_ASCII_PUNCT_INIT,
    [MMGR_ASCII_SPACE] = MMGR_ASCII_SPACE_INIT,
    [MMGR_ASCII_CTRL] = MMGR_ASCII_CTRL_INIT,
    [MMGR_ASCII_PRINT] = MMGR_ASCII_PRINT_INIT,
};

/**
 * @brief One class test.
 *
 * File local and staying that way. AsciiCfg in the header wears the same two fields and is not
 * this: that one is what the caller hands over, this one is what the body works with.
 */
typedef struct
{
    MmgrAsciiClass k; /**< The class being asked about. */
    uint8_t c;        /**< The byte. */
} AsciiCtx;

/**
 * @brief Is the byte in the class.
 * @param x The test.
 * @return MMGR_TRUE if it is. Bytes at or above 0x80 are in no class.
 *
 * One load, one shift and one and, on every width. An index past the last class is a caller that
 * has not decided what it is asking.
 */
MMGR_INLINE mmgr_bool ascii_in(const AsciiCtx *x)
{
    MMGR_ASSERT(x->k < MMGR_ASCII_CLASSES, "no such character class");

    const MmgrAsciiMask *const m = &s_class[x->k];
    return (mmgr_bool)((x->c < 0x80u) && (((m->b[x->c >> 3] >> (x->c & 7u)) & 1u) != 0u));
}

/* The namespace is a table of function pointers with the caller's config in their types, so this
   is what it points at. It builds the context and hands it to the body above.

   Parenthesised because the header defines a macro of this name for the call site, and the
   identifier here would otherwise sit immediately before a parenthesis and be taken for an
   invocation of it.

   It is nameable rather than file local because a static const table in the header has to be able
   to point at it, and a static const table is what gcc devirtualizes. Through an extern one every
   call from another translation unit is a load of the table, a load of the entry, and an indirect
   call it cannot see through. */

mmgr_bool (mmgr_ascii_in)(const AsciiCfg *c)
{
    return MMGR_CALL(ascii_in, AsciiCtx, .k = c->k, .c = c->c);
}
