// memmanager - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
#ifndef MMGR_ASCII_PERSONA_BITORUM_H
#define MMGR_ASCII_PERSONA_BITORUM_H

#include "config/mmgr_config.h"

MMGR_INCIPE_DECLS

/**
 * @file ascii_persona_bitorum.h
 * @brief Character classes as bitmaps. One shift and one and answers any of them.
 *
 * Every class costs the same. There is no cheap class and no expensive one, and no range chain
 * anywhere. ws() was six compares and a branch. digit() was two. Neither is now.
 *
 * Sixteen bytes, not two uint64. The obvious spelling is a pair of 64-bit halves indexed by bit 6,
 * and on x86 that is fine. This library also builds at MMGR_WORD_BITS 16, where a 64-bit shift is a
 * called routine and a 64-bit constant is four loads. Byte indexing is one load, one shift and one
 * and on every width, and needs no per-width spelling of the constants.
 *
 * Generated by tools/dev_env/gen_ascii_persona_bitorum.py from the predicates. These are exactly the
 * constants nobody can check by eye - the first three written out by hand had 'Z' missing from
 * ALPHA, and space, DEL and 0x1F wrongly in PUNCT.
 *
 * Bytes at or above 0x80 are in no class.
 */

/** @brief A 128-bit character class. */
typedef struct
{
    uint8_t b[16];
} MmgrAsciiMask;

MMGR_STATIC_ASSERT(sizeof(MmgrAsciiMask) == 16u, "an ASCII class mask is exactly 128 bits");

/** @brief 0-9 */
#define MMGR_ASCII_NUM_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}

/** @brief A-Z a-z */
#define MMGR_ASCII_ALPHA_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFE, 0xFF, 0xFF, 0x07, 0xFE, 0xFF, 0xFF, 0x07}}

/** @brief 0-9 A-Z a-z */
#define MMGR_ASCII_ALNUM_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x03, 0xFE, 0xFF, 0xFF, 0x07, 0xFE, 0xFF, 0xFF, 0x07}}

/** @brief A-Z */
#define MMGR_ASCII_UPPER_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFE, 0xFF, 0xFF, 0x07, 0x00, 0x00, 0x00, 0x00}}

/** @brief a-z */
#define MMGR_ASCII_LOWER_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFE, 0xFF, 0xFF, 0x07}}

/** @brief 0-9 A-F a-f */
#define MMGR_ASCII_HEX_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x03, 0x7E, 0x00, 0x00, 0x00, 0x7E, 0x00, 0x00, 0x00}}

/** @brief printable, not alphanumeric, not space */
#define MMGR_ASCII_PUNCT_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0xFE, 0xFF, 0x00, 0xFC, 0x01, 0x00, 0x00, 0xF8, 0x01, 0x00, 0x00, 0x78}}

/** @brief space tab newline vtab formfeed return */
#define MMGR_ASCII_SPACE_INIT                                            \
    {{0x00, 0x3E, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}

/** @brief space through ~ */
#define MMGR_ASCII_PRINT_INIT                                            \
    {{0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x7F}}

/** @brief below space, and DEL */
#define MMGR_ASCII_CTRL_INIT                                            \
    {{0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80}}

/** @brief Which class is being asked about. */
typedef enum
{
    MMGR_ASCII_NUM = 0,
    MMGR_ASCII_ALPHA,
    MMGR_ASCII_ALNUM,
    MMGR_ASCII_UPPER,
    MMGR_ASCII_LOWER,
    MMGR_ASCII_HEX,
    MMGR_ASCII_PUNCT,
    MMGR_ASCII_SPACE,
    MMGR_ASCII_CTRL,
    MMGR_ASCII_PRINT,
    MMGR_ASCII_CLASSES
} MmgrAsciiClass;

/**
 * @brief Is @p c in class @p k.
 * @param k The class.
 * @param c The byte.
 * @return MMGR_TRUE if it is. Bytes at or above 0x80 are in no class.
 *
 * The masks do not cross this header. A class is named by an index and answered by the file that
 * holds them, so no translation unit that asks the question carries a copy of the answer.
 */
mmgr_bool mmgr_ascii_in(MmgrAsciiClass k, uint8_t c);

MMGR_FINIS_DECLS

#endif
