// memmanager - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Generated by tools/dev_env/gen_ascii_persona_bitorum.py. Editing this by hand is undone the next
// time anyone runs the generator, and `harness.py generated` will say so before that happens.
#ifndef MMGR_ASCII_PERSONA_BITORUM_H
#define MMGR_ASCII_PERSONA_BITORUM_H

#include "config/mmgr_config.h"

MMGR_INCIPE_DECLS

/**
 * @file ascii_persona_bitorum.h
 * @brief Character classes as bitmaps. One shift and one and answers any of them.
 *
 * Every class costs the same. There is no cheap class and no expensive one, and no range chain
 * anywhere. ws() was six compares and a branch. digit() was two. Neither is now.
 *
 * Sixteen bytes, not two uint64. The obvious spelling is a pair of 64-bit halves indexed by bit 6,
 * and on x86 that is fine. This library also builds at MMGR_WORD_BITS 16, where a 64-bit shift is a
 * called routine and a 64-bit constant is four loads. Byte indexing is one load, one shift and one
 * and on every width, and needs no per-width spelling of the constants.
 *
 * Generated by tools/dev_env/gen_ascii_persona_bitorum.py from the predicates. These are exactly the
 * constants nobody can check by eye - the first three written out by hand had 'Z' missing from
 * ALPHA, and space, DEL and 0x1F wrongly in PUNCT.
 *
 * Bytes at or above 0x80 are in no class.
 *
 * The table is the whole surface. There are no free functions to call.
 */

/** @brief A 128-bit character class. */
typedef struct
{
    uint8_t b[16];
} MmgrAsciiMask;

MMGR_STATIC_ASSERT(sizeof(MmgrAsciiMask) == 16u, "an ASCII class mask is exactly 128 bits");

/** @brief Which class is being asked about. */
typedef enum
{
    MMGR_ASCII_NUM = 0,
    MMGR_ASCII_ALPHA,
    MMGR_ASCII_ALNUM,
    MMGR_ASCII_UPPER,
    MMGR_ASCII_LOWER,
    MMGR_ASCII_HEX,
    MMGR_ASCII_PUNCT,
    MMGR_ASCII_SPACE,
    MMGR_ASCII_CTRL,
    MMGR_ASCII_PRINT,
    MMGR_ASCII_CLASSES
} MmgrAsciiClass;

/** @brief Dispatch table. Addressed by offset, so the layout is asserted below. */
typedef struct
{
    mmgr_bool (*in)(MmgrAsciiClass k, uint8_t c);
} AsciiPersonaBitorumNs;
MMGR_NS_LAYOUT(AsciiPersonaBitorumNs, in);

/** @name The entries the table points at.
 *  @brief Nameable so a static const table can name them, and for no other reason. The table is
 *         still the whole surface: call through it.
 *
 *  Neither the masks nor the macros that spell them cross this header. A class is named by an
 *  index and answered by the file that holds them, so no translation unit that asks the question
 *  carries a copy of the answer, and none of them has ten more names to avoid.
 *  @{ */
mmgr_bool mmgr_ascii_in(MmgrAsciiClass k, uint8_t c);
/** @} */

/**
 * @brief Module namespace.
 *
 * static const, like every other module's. gcc devirtualizes a call through one down to the
 * inlined body and cannot do that through an extern one, where the table is in another
 * translation unit and every call is a load and an indirect jump.
 */
MMGR_NS AsciiPersonaBitorumNs ascii MMGR_UNUSED = {
    .in = mmgr_ascii_in,
};

MMGR_FINIS_DECLS

#endif
