/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "locus_carcerum/locus_carcerum.h"
#include "spatium/spatium.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_locus_carcerum_header_is_self_contained(void);
extern void test_the_namespace_is_wired(void);
extern void test_the_machinery_sits_below_the_arena(void);
extern void test_a_site_does_not_pay_for_the_ceiling(void);
extern void test_a_four_cellblock_site_builds_all_four(void);
extern void test_a_four_cellblock_site_lays_them_end_to_end(void);
extern void test_every_cellblock_of_a_four_cellblock_site_allocates_from_its_own_bytes(void);
extern void test_an_eight_cellblock_site_builds_and_allocates(void);
extern void test_two_sites_hold_separate_pools(void);
extern void test_init_records_the_site_it_was_given(void);
extern void test_the_build_lays_the_cellblocks_end_to_end(void);
extern void test_a_fresh_cellblock_is_empty_and_whole(void);
extern void test_align_up_rounds_to_a_whole_word(void);
extern void test_both_tiers_hand_out_aligned_addresses(void);
extern void test_the_persistent_tier_hands_out_the_bottom_and_walks_up(void);
extern void test_the_temporary_tier_hands_out_the_top_and_walks_down(void);
extern void test_the_two_tiers_allocate_from_the_same_gap(void);
extern void test_both_tiers_fail_closed(void);
extern void test_a_released_cell_is_reused(void);
extern void test_the_persistent_tier_releases_out_of_order(void);
extern void test_adjacent_empty_cells_merge(void);
extern void test_a_minimum_security_release_leaves_the_bytes_alone(void);
extern void test_a_maximum_security_release_zeroes_the_bytes_first(void);
extern void test_a_maximum_security_release_zeroes_the_whole_cell(void);
extern void test_the_zeroing_clears_exactly_what_it_was_given(void);
extern void test_a_mark_releases_everything_taken_after_it(void);
extern void test_marks_nest_because_the_caller_holds_them(void);
extern void test_reset_releases_the_whole_temporary_tier(void);
extern void test_who_owns_buf_tells_a_cellblock_from_its_neighbor(void);
extern void test_who_owns_buf_refuses_the_edges(void);
extern void test_the_cellblocks_do_not_share_a_fill_point(void);
extern void test_a_span_over_cellblock_bytes_carries_the_cellblock_address(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/locus_carcerum/test_locus_carcerum\\test_locus_carcerum.c");
  run_test(test_locus_carcerum_header_is_self_contained, "test_locus_carcerum_header_is_self_contained", 51);
  run_test(test_the_namespace_is_wired, "test_the_namespace_is_wired", 56);
  run_test(test_the_machinery_sits_below_the_arena, "test_the_machinery_sits_below_the_arena", 64);
  run_test(test_a_site_does_not_pay_for_the_ceiling, "test_a_site_does_not_pay_for_the_ceiling", 70);
  run_test(test_a_four_cellblock_site_builds_all_four, "test_a_four_cellblock_site_builds_all_four", 77);
  run_test(test_a_four_cellblock_site_lays_them_end_to_end, "test_a_four_cellblock_site_lays_them_end_to_end", 83);
  run_test(test_every_cellblock_of_a_four_cellblock_site_allocates_from_its_own_bytes, "test_every_cellblock_of_a_four_cellblock_site_allocates_from_its_own_bytes", 91);
  run_test(test_an_eight_cellblock_site_builds_and_allocates, "test_an_eight_cellblock_site_builds_and_allocates", 106);
  run_test(test_two_sites_hold_separate_pools, "test_two_sites_hold_separate_pools", 122);
  run_test(test_init_records_the_site_it_was_given, "test_init_records_the_site_it_was_given", 128);
  run_test(test_the_build_lays_the_cellblocks_end_to_end, "test_the_build_lays_the_cellblocks_end_to_end", 135);
  run_test(test_a_fresh_cellblock_is_empty_and_whole, "test_a_fresh_cellblock_is_empty_and_whole", 143);
  run_test(test_align_up_rounds_to_a_whole_word, "test_align_up_rounds_to_a_whole_word", 150);
  run_test(test_both_tiers_hand_out_aligned_addresses, "test_both_tiers_hand_out_aligned_addresses", 158);
  run_test(test_the_persistent_tier_hands_out_the_bottom_and_walks_up, "test_the_persistent_tier_hands_out_the_bottom_and_walks_up", 175);
  run_test(test_the_temporary_tier_hands_out_the_top_and_walks_down, "test_the_temporary_tier_hands_out_the_top_and_walks_down", 184);
  run_test(test_the_two_tiers_allocate_from_the_same_gap, "test_the_two_tiers_allocate_from_the_same_gap", 193);
  run_test(test_both_tiers_fail_closed, "test_both_tiers_fail_closed", 203);
  run_test(test_a_released_cell_is_reused, "test_a_released_cell_is_reused", 211);
  run_test(test_the_persistent_tier_releases_out_of_order, "test_the_persistent_tier_releases_out_of_order", 223);
  run_test(test_adjacent_empty_cells_merge, "test_adjacent_empty_cells_merge", 241);
  run_test(test_a_minimum_security_release_leaves_the_bytes_alone, "test_a_minimum_security_release_leaves_the_bytes_alone", 256);
  run_test(test_a_maximum_security_release_zeroes_the_bytes_first, "test_a_maximum_security_release_zeroes_the_bytes_first", 272);
  run_test(test_a_maximum_security_release_zeroes_the_whole_cell, "test_a_maximum_security_release_zeroes_the_whole_cell", 288);
  run_test(test_the_zeroing_clears_exactly_what_it_was_given, "test_the_zeroing_clears_exactly_what_it_was_given", 306);
  run_test(test_a_mark_releases_everything_taken_after_it, "test_a_mark_releases_everything_taken_after_it", 326);
  run_test(test_marks_nest_because_the_caller_holds_them, "test_marks_nest_because_the_caller_holds_them", 338);
  run_test(test_reset_releases_the_whole_temporary_tier, "test_reset_releases_the_whole_temporary_tier", 355);
  run_test(test_who_owns_buf_tells_a_cellblock_from_its_neighbor, "test_who_owns_buf_tells_a_cellblock_from_its_neighbor", 363);
  run_test(test_who_owns_buf_refuses_the_edges, "test_who_owns_buf_refuses_the_edges", 374);
  run_test(test_the_cellblocks_do_not_share_a_fill_point, "test_the_cellblocks_do_not_share_a_fill_point", 386);
  run_test(test_a_span_over_cellblock_bytes_carries_the_cellblock_address, "test_a_span_over_cellblock_bytes_carries_the_cellblock_address", 394);

  return UNITY_END();
}
