/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "memoria_operor/memoria_operor.h"
#include <stdio.h>
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_memor_header_is_self_contained(void);
extern void test_memor_namespace_is_wired(void);
extern void test_cpy_matches_memcpy_at_every_length(void);
extern void test_cpy_matches_memcpy_at_every_offset(void);
extern void test_cpy_of_nothing_touches_nothing(void);
extern void test_move_matches_memmove_when_the_regions_do_not_touch(void);
extern void test_move_matches_memmove_overlapping_forwards(void);
extern void test_move_matches_memmove_overlapping_backwards(void);
extern void test_move_onto_itself_changes_nothing(void);
extern void test_move_of_nothing_touches_nothing(void);
extern void test_move_of_regions_that_end_exactly_where_the_other_starts(void);
extern void test_cmp_agrees_with_memcmp_on_the_sign(void);
extern void test_cmp_finds_a_difference_at_every_position(void);
extern void test_cmp_of_nothing_is_equal(void);
extern void test_cmp_reads_no_further_than_it_was_told(void);
extern void test_chr_matches_memchr_at_every_position(void);
extern void test_chr_of_a_byte_that_is_not_there(void);
extern void test_chr_of_nothing_finds_nothing(void);
extern void test_chr_finds_a_zero_byte(void);
extern void test_set_matches_memset_at_every_length(void);
extern void test_set_matches_memset_at_every_offset(void);
extern void test_set_keeps_only_the_low_byte_of_its_value(void);
extern void test_zero_is_set_of_zero(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/memoria_operor/test_memoria_operor\\test_memoria_operor.c");
  run_test(test_memor_header_is_self_contained, "test_memor_header_is_self_contained", 59);
  run_test(test_memor_namespace_is_wired, "test_memor_namespace_is_wired", 64);
  run_test(test_cpy_matches_memcpy_at_every_length, "test_cpy_matches_memcpy_at_every_length", 76);
  run_test(test_cpy_matches_memcpy_at_every_offset, "test_cpy_matches_memcpy_at_every_offset", 90);
  run_test(test_cpy_of_nothing_touches_nothing, "test_cpy_of_nothing_touches_nothing", 109);
  run_test(test_move_matches_memmove_when_the_regions_do_not_touch, "test_move_matches_memmove_when_the_regions_do_not_touch", 122);
  run_test(test_move_matches_memmove_overlapping_forwards, "test_move_matches_memmove_overlapping_forwards", 129);
  run_test(test_move_matches_memmove_overlapping_backwards, "test_move_matches_memmove_overlapping_backwards", 143);
  run_test(test_move_onto_itself_changes_nothing, "test_move_onto_itself_changes_nothing", 157);
  run_test(test_move_of_nothing_touches_nothing, "test_move_of_nothing_touches_nothing", 163);
  run_test(test_move_of_regions_that_end_exactly_where_the_other_starts, "test_move_of_regions_that_end_exactly_where_the_other_starts", 169);
  run_test(test_cmp_agrees_with_memcmp_on_the_sign, "test_cmp_agrees_with_memcmp_on_the_sign", 181);
  run_test(test_cmp_finds_a_difference_at_every_position, "test_cmp_finds_a_difference_at_every_position", 195);
  run_test(test_cmp_of_nothing_is_equal, "test_cmp_of_nothing_is_equal", 212);
  run_test(test_cmp_reads_no_further_than_it_was_told, "test_cmp_reads_no_further_than_it_was_told", 217);
  run_test(test_chr_matches_memchr_at_every_position, "test_chr_matches_memchr_at_every_position", 229);
  run_test(test_chr_of_a_byte_that_is_not_there, "test_chr_of_a_byte_that_is_not_there", 250);
  run_test(test_chr_of_nothing_finds_nothing, "test_chr_of_nothing_finds_nothing", 266);
  run_test(test_chr_finds_a_zero_byte, "test_chr_finds_a_zero_byte", 271);
  run_test(test_set_matches_memset_at_every_length, "test_set_matches_memset_at_every_length", 281);
  run_test(test_set_matches_memset_at_every_offset, "test_set_matches_memset_at_every_offset", 292);
  run_test(test_set_keeps_only_the_low_byte_of_its_value, "test_set_keeps_only_the_low_byte_of_its_value", 303);
  run_test(test_zero_is_set_of_zero, "test_zero_is_set_of_zero", 310);

  return UNITY_END();
}
