/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cellularum_laboro/cellularum_laboro.h"
#include "numeros_scribo/numeros_scribo.h"
#include "verba_scribo/verba_scribo.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_built_text_reads_back_at_the_length_it_reported(void);
extern void test_scanner_finds_what_the_builder_wrote(void);
extern void test_case_folding_agrees_across_builder_and_scanner(void);
extern void test_appending_keeps_every_earlier_field_findable(void);
extern void test_a_builder_overflow_leaves_nothing_for_the_scanner(void);
extern void test_every_rendered_number_is_found_by_the_scanner(void);
extern void test_escaped_output_is_still_scannable(void);
extern void test_an_empty_render_reports_nothing_written(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/integration/test_text_pipeline\\test_text_pipeline.c");
  run_test(test_built_text_reads_back_at_the_length_it_reported, "test_built_text_reads_back_at_the_length_it_reported", 10);
  run_test(test_scanner_finds_what_the_builder_wrote, "test_scanner_finds_what_the_builder_wrote", 21);
  run_test(test_case_folding_agrees_across_builder_and_scanner, "test_case_folding_agrees_across_builder_and_scanner", 36);
  run_test(test_appending_keeps_every_earlier_field_findable, "test_appending_keeps_every_earlier_field_findable", 51);
  run_test(test_a_builder_overflow_leaves_nothing_for_the_scanner, "test_a_builder_overflow_leaves_nothing_for_the_scanner", 72);
  run_test(test_every_rendered_number_is_found_by_the_scanner, "test_every_rendered_number_is_found_by_the_scanner", 84);
  run_test(test_escaped_output_is_still_scannable, "test_escaped_output_is_still_scannable", 104);
  run_test(test_an_empty_render_reports_nothing_written, "test_an_empty_render_reports_nothing_written", 128);

  return UNITY_END();
}
