/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cellularum_laboro/cellularum_laboro.h"
#include "memoria_operor/memoria_operor.h"
#include "verbum_scrutor/verbum_scrutor.h"
#include "guard_page.h"
#include "oracle_divergence.h"
#include <stdio.h>
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_the_guard_is_armed(void);
extern void test_len_stays_inside_the_reserved_extent(void);
extern void test_chr_stays_inside_the_reserved_extent(void);
extern void test_eq_stays_inside_the_reserved_extent(void);
extern void test_starts_stays_inside_the_reserved_extent(void);
extern void test_diff_stays_inside_the_reserved_extent(void);
extern void test_copy_stays_inside_the_reserved_extent(void);
extern void test_memor_cmp_stays_inside_the_reserved_extent(void);
extern void test_memor_chr_stays_inside_the_reserved_extent(void);
extern void test_find_stays_inside_the_raw_cap(void);
extern void test_has_stays_inside_the_raw_cap(void);
extern void test_find_still_finds_things_with_the_buffer_flush_to_the_guard(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/integration/test_read_bounds\\test_read_bounds.c");
  run_test(test_the_guard_is_armed, "test_the_guard_is_armed", 149);
  run_test(test_len_stays_inside_the_reserved_extent, "test_len_stays_inside_the_reserved_extent", 163);
  run_test(test_chr_stays_inside_the_reserved_extent, "test_chr_stays_inside_the_reserved_extent", 169);
  run_test(test_eq_stays_inside_the_reserved_extent, "test_eq_stays_inside_the_reserved_extent", 175);
  run_test(test_starts_stays_inside_the_reserved_extent, "test_starts_stays_inside_the_reserved_extent", 182);
  run_test(test_diff_stays_inside_the_reserved_extent, "test_diff_stays_inside_the_reserved_extent", 188);
  run_test(test_copy_stays_inside_the_reserved_extent, "test_copy_stays_inside_the_reserved_extent", 194);
  run_test(test_memor_cmp_stays_inside_the_reserved_extent, "test_memor_cmp_stays_inside_the_reserved_extent", 206);
  run_test(test_memor_chr_stays_inside_the_reserved_extent, "test_memor_chr_stays_inside_the_reserved_extent", 212);
  run_test(test_find_stays_inside_the_raw_cap, "test_find_stays_inside_the_raw_cap", 254);
  run_test(test_has_stays_inside_the_raw_cap, "test_has_stays_inside_the_raw_cap", 260);
  run_test(test_find_still_finds_things_with_the_buffer_flush_to_the_guard, "test_find_still_finds_things_with_the_buffer_flush_to_the_guard", 266);

  return UNITY_END();
}
