/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "memoria_anularis/memoria_anularis.h"
#include <stdint.h>
#include <stdio.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_the_reference_queue_this_suite_relies_on_is_itself_right(void);
extern void test_a_long_run_of_writes_and_reads_delivers_every_byte_in_order(void);
extern void test_a_byte_at_a_time_comes_out_in_the_order_it_went_in(void);
extern void test_a_peek_returns_what_a_read_would_and_moves_nothing(void);
extern void test_a_span_too_large_is_refused_whole(void);
extern void test_segments_come_back_in_order_and_tile_the_buffer(void);
extern void test_the_producer_is_refused_once_every_segment_is_in_flight(void);
extern void test_the_loculus_masks_match_a_bitset_kept_alongside(void);
extern void test_the_lowest_set_bit_matches_a_bit_at_a_time_scan(void);
extern void test_a_held_loculus_hands_back_the_region_it_was_given(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/accuracy/test_memoria_anularis_accuracy\\test_memoria_anularis_accuracy.c");
  run_test(test_the_reference_queue_this_suite_relies_on_is_itself_right, "test_the_reference_queue_this_suite_relies_on_is_itself_right", 208);
  run_test(test_a_long_run_of_writes_and_reads_delivers_every_byte_in_order, "test_a_long_run_of_writes_and_reads_delivers_every_byte_in_order", 243);
  run_test(test_a_byte_at_a_time_comes_out_in_the_order_it_went_in, "test_a_byte_at_a_time_comes_out_in_the_order_it_went_in", 324);
  run_test(test_a_peek_returns_what_a_read_would_and_moves_nothing, "test_a_peek_returns_what_a_read_would_and_moves_nothing", 374);
  run_test(test_a_span_too_large_is_refused_whole, "test_a_span_too_large_is_refused_whole", 441);
  run_test(test_segments_come_back_in_order_and_tile_the_buffer, "test_segments_come_back_in_order_and_tile_the_buffer", 509);
  run_test(test_the_producer_is_refused_once_every_segment_is_in_flight, "test_the_producer_is_refused_once_every_segment_is_in_flight", 575);
  run_test(test_the_loculus_masks_match_a_bitset_kept_alongside, "test_the_loculus_masks_match_a_bitset_kept_alongside", 615);
  run_test(test_the_lowest_set_bit_matches_a_bit_at_a_time_scan, "test_the_lowest_set_bit_matches_a_bit_at_a_time_scan", 690);
  run_test(test_a_held_loculus_hands_back_the_region_it_was_given, "test_a_held_loculus_hands_back_the_region_it_was_given", 729);

  return UNITY_END();
}
