/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "spatium/spatium.h"
#include <stdint.h>
#include <stdio.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_the_constructors_build_the_spans_they_are_documented_to(void);
extern void test_the_span_beginning_a_count_in_names_the_right_bytes(void);
extern void test_the_span_covering_the_first_count_names_the_right_bytes(void);
extern void test_the_read_span_over_what_was_written_covers_the_right_bytes(void);
extern void test_the_read_span_over_everything_written_covers_the_cursor(void);
extern void test_the_predicates_test_what_they_are_documented_to(void);
extern void test_a_derived_span_is_a_second_view_of_the_same_bytes(void);
extern void test_a_rewind_returns_the_cursor_and_leaves_the_bytes(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/accuracy/test_spatium_accuracy\\test_spatium_accuracy.c");
  run_test(test_the_constructors_build_the_spans_they_are_documented_to, "test_the_constructors_build_the_spans_they_are_documented_to", 146);
  run_test(test_the_span_beginning_a_count_in_names_the_right_bytes, "test_the_span_beginning_a_count_in_names_the_right_bytes", 167);
  run_test(test_the_span_covering_the_first_count_names_the_right_bytes, "test_the_span_covering_the_first_count_names_the_right_bytes", 211);
  run_test(test_the_read_span_over_what_was_written_covers_the_right_bytes, "test_the_read_span_over_what_was_written_covers_the_right_bytes", 255);
  run_test(test_the_read_span_over_everything_written_covers_the_cursor, "test_the_read_span_over_everything_written_covers_the_cursor", 290);
  run_test(test_the_predicates_test_what_they_are_documented_to, "test_the_predicates_test_what_they_are_documented_to", 322);
  run_test(test_a_derived_span_is_a_second_view_of_the_same_bytes, "test_a_derived_span_is_a_second_view_of_the_same_bytes", 363);
  run_test(test_a_rewind_returns_the_cursor_and_leaves_the_bytes, "test_a_rewind_returns_the_cursor_and_leaves_the_bytes", 422);

  return UNITY_END();
}
