/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "carceribus/carceribus.h"
#include "spatium/spatium.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_carceribus_header_is_self_contained(void);
extern void test_the_namespace_is_wired(void);
extern void test_the_machinery_sits_below_the_arena(void);
extern void test_a_region_does_not_pay_for_the_ceiling(void);
extern void test_a_four_pool_region_carves_all_four(void);
extern void test_a_four_pool_region_lays_them_end_to_end(void);
extern void test_every_pool_of_a_four_pool_region_takes_from_its_own_bytes(void);
extern void test_an_eight_pool_region_carves_and_takes(void);
extern void test_two_regions_may_share_pool_names(void);
extern void test_init_records_the_region_it_was_given(void);
extern void test_the_carve_lays_the_pools_end_to_end(void);
extern void test_a_fresh_pool_is_empty_and_whole(void);
extern void test_align_up_rounds_to_a_whole_word(void);
extern void test_both_ends_hand_out_aligned_addresses(void);
extern void test_persist_hands_out_the_bottom_and_walks_up(void);
extern void test_interim_hands_out_the_top_and_walks_down(void);
extern void test_the_two_ends_take_from_the_same_middle(void);
extern void test_both_ends_fail_closed(void);
extern void test_a_released_block_is_reused(void);
extern void test_persist_releases_out_of_order(void);
extern void test_adjacent_free_blocks_merge(void);
extern void test_a_plain_release_leaves_the_bytes_alone(void);
extern void test_a_secura_release_zeroes_the_bytes_first(void);
extern void test_a_secura_release_wipes_the_whole_block(void);
extern void test_the_wipe_clears_exactly_what_it_was_given(void);
extern void test_a_mark_gives_back_everything_taken_after_it(void);
extern void test_marks_nest_because_the_caller_holds_them(void);
extern void test_reset_gives_the_whole_interim_end_back(void);
extern void test_owns_tells_a_pool_from_its_neighbour(void);
extern void test_owns_refuses_the_edges(void);
extern void test_the_pools_do_not_share_a_fill_point(void);
extern void test_a_span_over_pool_bytes_carries_the_pool_address(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/carceribus/test_carceribus\\test_carceribus.c");
  run_test(test_carceribus_header_is_self_contained, "test_carceribus_header_is_self_contained", 47);
  run_test(test_the_namespace_is_wired, "test_the_namespace_is_wired", 52);
  run_test(test_the_machinery_sits_below_the_arena, "test_the_machinery_sits_below_the_arena", 58);
  run_test(test_a_region_does_not_pay_for_the_ceiling, "test_a_region_does_not_pay_for_the_ceiling", 70);
  run_test(test_a_four_pool_region_carves_all_four, "test_a_four_pool_region_carves_all_four", 79);
  run_test(test_a_four_pool_region_lays_them_end_to_end, "test_a_four_pool_region_lays_them_end_to_end", 88);
  run_test(test_every_pool_of_a_four_pool_region_takes_from_its_own_bytes, "test_every_pool_of_a_four_pool_region_takes_from_its_own_bytes", 102);
  run_test(test_an_eight_pool_region_carves_and_takes, "test_an_eight_pool_region_carves_and_takes", 123);
  run_test(test_two_regions_may_share_pool_names, "test_two_regions_may_share_pool_names", 142);
  run_test(test_init_records_the_region_it_was_given, "test_init_records_the_region_it_was_given", 148);
  run_test(test_the_carve_lays_the_pools_end_to_end, "test_the_carve_lays_the_pools_end_to_end", 155);
  run_test(test_a_fresh_pool_is_empty_and_whole, "test_a_fresh_pool_is_empty_and_whole", 163);
  run_test(test_align_up_rounds_to_a_whole_word, "test_align_up_rounds_to_a_whole_word", 170);
  run_test(test_both_ends_hand_out_aligned_addresses, "test_both_ends_hand_out_aligned_addresses", 181);
  run_test(test_persist_hands_out_the_bottom_and_walks_up, "test_persist_hands_out_the_bottom_and_walks_up", 199);
  run_test(test_interim_hands_out_the_top_and_walks_down, "test_interim_hands_out_the_top_and_walks_down", 208);
  run_test(test_the_two_ends_take_from_the_same_middle, "test_the_two_ends_take_from_the_same_middle", 217);
  run_test(test_both_ends_fail_closed, "test_both_ends_fail_closed", 230);
  run_test(test_a_released_block_is_reused, "test_a_released_block_is_reused", 241);
  run_test(test_persist_releases_out_of_order, "test_persist_releases_out_of_order", 256);
  run_test(test_adjacent_free_blocks_merge, "test_adjacent_free_blocks_merge", 278);
  run_test(test_a_plain_release_leaves_the_bytes_alone, "test_a_plain_release_leaves_the_bytes_alone", 294);
  run_test(test_a_secura_release_zeroes_the_bytes_first, "test_a_secura_release_zeroes_the_bytes_first", 313);
  run_test(test_a_secura_release_wipes_the_whole_block, "test_a_secura_release_wipes_the_whole_block", 332);
  run_test(test_the_wipe_clears_exactly_what_it_was_given, "test_the_wipe_clears_exactly_what_it_was_given", 350);
  run_test(test_a_mark_gives_back_everything_taken_after_it, "test_a_mark_gives_back_everything_taken_after_it", 370);
  run_test(test_marks_nest_because_the_caller_holds_them, "test_marks_nest_because_the_caller_holds_them", 385);
  run_test(test_reset_gives_the_whole_interim_end_back, "test_reset_gives_the_whole_interim_end_back", 402);
  run_test(test_owns_tells_a_pool_from_its_neighbour, "test_owns_tells_a_pool_from_its_neighbour", 410);
  run_test(test_owns_refuses_the_edges, "test_owns_refuses_the_edges", 421);
  run_test(test_the_pools_do_not_share_a_fill_point, "test_the_pools_do_not_share_a_fill_point", 433);
  run_test(test_a_span_over_pool_bytes_carries_the_pool_address, "test_a_span_over_pool_bytes_carries_the_pool_address", 441);

  return UNITY_END();
}
