/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "carceribus/carceribus.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_carceribus_header_is_self_contained(void);
extern void test_align_up_rounds_to_the_grain(void);
extern void test_a_fresh_tenant_is_empty(void);
extern void test_init_aligns_the_base_up_and_loses_the_slack(void);
extern void test_init_of_a_region_too_small_to_align_leaves_nothing(void);
extern void test_persist_hands_out_zeroed_bytes(void);
extern void test_a_zero_sized_persist_still_gives_a_block(void);
extern void test_persist_blocks_do_not_overlap(void);
extern void test_a_freed_block_is_reused(void);
extern void test_a_large_free_block_splits(void);
extern void test_an_exact_fit_does_not_split(void);
extern void test_freeing_null_is_a_no_op(void);
extern void test_freeing_twice_does_not_double_count(void);
extern void test_adjacent_free_blocks_coalesce(void);
extern void test_persist_fails_rather_than_meeting_the_other_end(void);
extern void test_interim_grows_down_from_the_top(void);
extern void test_interim_honours_alignment(void);
extern void test_a_zero_sized_interim_still_gives_bytes(void);
extern void test_interim_mark_and_release(void);
extern void test_a_stale_or_forward_mark_is_ignored(void);
extern void test_interim_reset_releases_everything(void);
extern void test_interim_fails_rather_than_meeting_the_other_end(void);
extern void test_the_two_ends_meet_and_stop(void);
extern void test_owns_rejects_what_it_did_not_hand_out(void);
extern void test_free_space_falls_as_it_is_taken(void);
extern void test_a_set_starts_empty(void);
extern void test_a_set_takes_regions_until_it_is_full(void);
extern void test_a_set_refuses_a_region_too_small_to_hold_anything(void);
extern void test_a_set_hands_out_from_its_regions(void);
extern void test_a_set_mark_covers_every_region(void);
extern void test_a_set_reset_releases_every_region(void);
extern void test_a_set_request_larger_than_any_region_fails(void);
extern void test_a_persist_request_walks_past_a_block_that_is_still_in_use(void);
extern void test_a_persist_request_walks_past_a_free_block_that_is_too_small(void);
extern void test_a_reused_block_is_split_when_there_is_enough_left_over(void);
extern void test_a_persist_request_larger_than_the_tenant_is_refused(void);
extern void test_a_persist_request_that_would_meet_the_interim_end_is_refused(void);
extern void test_releasing_the_same_block_twice_is_ignored(void);
extern void test_releasing_nothing_is_ignored(void);
extern void test_free_space_is_zero_once_the_two_ends_meet(void);
extern void test_free_space_never_reports_less_than_a_header(void);
extern void test_an_aligned_interim_request_that_does_not_fit_is_refused(void);
extern void test_owns_says_no_to_addresses_on_either_side(void);
extern void test_a_set_release_finds_the_region_the_pointer_came_from(void);
extern void test_a_set_release_of_an_address_it_does_not_hold(void);
extern void test_a_set_release_on_an_empty_set(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/unit/carceribus/test_carceribus\\test_carceribus.c");
  run_test(test_carceribus_header_is_self_contained, "test_carceribus_header_is_self_contained", 27);
  run_test(test_align_up_rounds_to_the_grain, "test_align_up_rounds_to_the_grain", 32);
  run_test(test_a_fresh_tenant_is_empty, "test_a_fresh_tenant_is_empty", 40);
  run_test(test_init_aligns_the_base_up_and_loses_the_slack, "test_init_aligns_the_base_up_and_loses_the_slack", 47);
  run_test(test_init_of_a_region_too_small_to_align_leaves_nothing, "test_init_of_a_region_too_small_to_align_leaves_nothing", 55);
  run_test(test_persist_hands_out_zeroed_bytes, "test_persist_hands_out_zeroed_bytes", 63);
  run_test(test_a_zero_sized_persist_still_gives_a_block, "test_a_zero_sized_persist_still_gives_a_block", 75);
  run_test(test_persist_blocks_do_not_overlap, "test_persist_blocks_do_not_overlap", 81);
  run_test(test_a_freed_block_is_reused, "test_a_freed_block_is_reused", 90);
  run_test(test_a_large_free_block_splits, "test_a_large_free_block_splits", 103);
  run_test(test_an_exact_fit_does_not_split, "test_an_exact_fit_does_not_split", 119);
  run_test(test_freeing_null_is_a_no_op, "test_freeing_null_is_a_no_op", 131);
  run_test(test_freeing_twice_does_not_double_count, "test_freeing_twice_does_not_double_count", 138);
  run_test(test_adjacent_free_blocks_coalesce, "test_adjacent_free_blocks_coalesce", 147);
  run_test(test_persist_fails_rather_than_meeting_the_other_end, "test_persist_fails_rather_than_meeting_the_other_end", 164);
  run_test(test_interim_grows_down_from_the_top, "test_interim_grows_down_from_the_top", 169);
  run_test(test_interim_honours_alignment, "test_interim_honours_alignment", 181);
  run_test(test_a_zero_sized_interim_still_gives_bytes, "test_a_zero_sized_interim_still_gives_bytes", 193);
  run_test(test_interim_mark_and_release, "test_interim_mark_and_release", 198);
  run_test(test_a_stale_or_forward_mark_is_ignored, "test_a_stale_or_forward_mark_is_ignored", 212);
  run_test(test_interim_reset_releases_everything, "test_interim_reset_releases_everything", 224);
  run_test(test_interim_fails_rather_than_meeting_the_other_end, "test_interim_fails_rather_than_meeting_the_other_end", 231);
  run_test(test_the_two_ends_meet_and_stop, "test_the_two_ends_meet_and_stop", 237);
  run_test(test_owns_rejects_what_it_did_not_hand_out, "test_owns_rejects_what_it_did_not_hand_out", 252);
  run_test(test_free_space_falls_as_it_is_taken, "test_free_space_falls_as_it_is_taken", 259);
  run_test(test_a_set_starts_empty, "test_a_set_starts_empty", 270);
  run_test(test_a_set_takes_regions_until_it_is_full, "test_a_set_takes_regions_until_it_is_full", 281);
  run_test(test_a_set_refuses_a_region_too_small_to_hold_anything, "test_a_set_refuses_a_region_too_small_to_hold_anything", 298);
  run_test(test_a_set_hands_out_from_its_regions, "test_a_set_hands_out_from_its_regions", 305);
  run_test(test_a_set_mark_covers_every_region, "test_a_set_mark_covers_every_region", 330);
  run_test(test_a_set_reset_releases_every_region, "test_a_set_reset_releases_every_region", 345);
  run_test(test_a_set_request_larger_than_any_region_fails, "test_a_set_request_larger_than_any_region_fails", 356);
  run_test(test_a_persist_request_walks_past_a_block_that_is_still_in_use, "test_a_persist_request_walks_past_a_block_that_is_still_in_use", 373);
  run_test(test_a_persist_request_walks_past_a_free_block_that_is_too_small, "test_a_persist_request_walks_past_a_free_block_that_is_too_small", 388);
  run_test(test_a_reused_block_is_split_when_there_is_enough_left_over, "test_a_reused_block_is_split_when_there_is_enough_left_over", 407);
  run_test(test_a_persist_request_larger_than_the_tenant_is_refused, "test_a_persist_request_larger_than_the_tenant_is_refused", 422);
  run_test(test_a_persist_request_that_would_meet_the_interim_end_is_refused, "test_a_persist_request_that_would_meet_the_interim_end_is_refused", 427);
  run_test(test_releasing_the_same_block_twice_is_ignored, "test_releasing_the_same_block_twice_is_ignored", 434);
  run_test(test_releasing_nothing_is_ignored, "test_releasing_nothing_is_ignored", 449);
  run_test(test_free_space_is_zero_once_the_two_ends_meet, "test_free_space_is_zero_once_the_two_ends_meet", 460);
  run_test(test_free_space_never_reports_less_than_a_header, "test_free_space_never_reports_less_than_a_header", 472);
  run_test(test_an_aligned_interim_request_that_does_not_fit_is_refused, "test_an_aligned_interim_request_that_does_not_fit_is_refused", 485);
  run_test(test_owns_says_no_to_addresses_on_either_side, "test_owns_says_no_to_addresses_on_either_side", 495);
  run_test(test_a_set_release_finds_the_region_the_pointer_came_from, "test_a_set_release_finds_the_region_the_pointer_came_from", 512);
  run_test(test_a_set_release_of_an_address_it_does_not_hold, "test_a_set_release_of_an_address_it_does_not_hold", 529);
  run_test(test_a_set_release_on_an_empty_set, "test_a_set_release_on_an_empty_set", 541);

  return UNITY_END();
}
