/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "confinium_exclusivum_infinitas/confinium_exclusivum_infinitas.h"
#include "guard_page.h"
#include <stdio.h>
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_the_guard_is_armed(void);
extern void test_the_ring_stays_inside_its_buffer_at_every_head(void);
extern void test_a_drain_stays_inside_the_destination_it_was_given(void);
extern void test_a_fill_stays_inside_the_source_it_was_given(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/integration/test_ring_bounds\\test_ring_bounds.c");
  run_test(test_the_guard_is_armed, "test_the_guard_is_armed", 131);
  run_test(test_the_ring_stays_inside_its_buffer_at_every_head, "test_the_ring_stays_inside_its_buffer_at_every_head", 150);
  run_test(test_a_drain_stays_inside_the_destination_it_was_given, "test_a_drain_stays_inside_the_destination_it_was_given", 178);
  run_test(test_a_fill_stays_inside_the_source_it_was_given, "test_a_fill_stays_inside_the_source_it_was_given", 208);

  return UNITY_END();
}
