/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "transformo/transformo.h"
#include <stdint.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_the_exact_arithmetic_this_suite_relies_on_is_itself_right(void);
extern void test_a_product_a_double_holds_exactly_comes_back_exactly(void);
extern void test_a_negative_exponent_that_ends_in_binary_is_exact(void);
extern void test_the_sign_changes_one_bit_and_nothing_else(void);
extern void test_the_integer_entry_returns_the_exact_product(void);
extern void test_a_binary_exponent_shifts_the_integer_result(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/accuracy/test_transformo_accuracy\\test_transformo_accuracy.c");
  run_test(test_the_exact_arithmetic_this_suite_relies_on_is_itself_right, "test_the_exact_arithmetic_this_suite_relies_on_is_itself_right", 130);
  run_test(test_a_product_a_double_holds_exactly_comes_back_exactly, "test_a_product_a_double_holds_exactly_comes_back_exactly", 155);
  run_test(test_a_negative_exponent_that_ends_in_binary_is_exact, "test_a_negative_exponent_that_ends_in_binary_is_exact", 195);
  run_test(test_the_sign_changes_one_bit_and_nothing_else, "test_the_sign_changes_one_bit_and_nothing_else", 221);
  run_test(test_the_integer_entry_returns_the_exact_product, "test_the_integer_entry_returns_the_exact_product", 244);
  run_test(test_a_binary_exponent_shifts_the_integer_result, "test_a_binary_exponent_shifts_the_integer_result", 273);

  return UNITY_END();
}
