/* MMgr - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
 * SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial OR LicenseRef-Educational
 *
 * Every use falls under AGPL-3.0-or-later unless you hold explicit permission, which is either a
 * negotiated commercial licensing contract or an educator's license issued to you personally.
 */
/**
 * @file praet_scenarios.h
 * @brief Correctness scenarios for the scripted DMA engine, and the outcome each one must produce.
 * @author dstroy0 (Douglas Quigg) <dquigg123@gmail.com>
 * @date 2026-09-01
 *
 * @warning Generated by tools/dev_env/gen_praet_scenarios.py. An edit here is discarded the next
 *          time that runs.
 * @note Each scenario appears twice, once per arm. The fixture is identical and only the arm
 *       differs, so a row that disagrees between the two is the arm and nothing else.
 * @note The expectations are computed by the generator, walking each program against its script.
 *       Nothing in C derives them.
 * @note The first entry is the control. It must come out clean, and if it does not, no other row in
 *       this table can be read.
 */
#ifndef MMGR_TEST_PRAET_SCENARIOS_H
#define MMGR_TEST_PRAET_SCENARIOS_H

#include "praet_engine.h"

EMBED_BEGIN_DECLS

/** @brief Calls the control_one_transfer_completes case makes. */
static const PraetProgramStep praet_program_control_one_transfer_completes[] = {
    {0u, 0u, 0u},
    {1u, 0u, 64u},
    {3u, 0u, 0u},
    {2u, 0u, 0u},
};

/** @brief Engine script for the control_one_transfer_completes case. */
static const PraetEngineStep praet_steps_control_one_transfer_completes[] = {
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {1u, 0u, 1u, 2u, 1u, 64u, 0u, 0u, 0u},
    {3u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {2u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
};

/** @brief Channels the control_one_transfer_completes_interrupt completions must arrive on, in order. */
static const uint8_t praet_order_control_one_transfer_completes_interrupt[] = {0u};

/** @brief Channels the control_one_transfer_completes_software completions must arrive on, in order. */
static const uint8_t praet_order_control_one_transfer_completes_software[] = {0u};

/** @brief Calls the refuse_the_open case makes. */
static const PraetProgramStep praet_program_refuse_the_open[] = {
    {0u, 0u, 0u},
    {1u, 0u, 64u},
    {3u, 0u, 0u},
    {2u, 0u, 0u},
};

/** @brief Engine script for the refuse_the_open case. */
static const PraetEngineStep praet_steps_refuse_the_open[] = {
    {0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u},
    {1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u},
    {3u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {2u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
};

/** @brief Channels the refuse_the_open_interrupt completions must arrive on, in order. */
static const uint8_t praet_order_refuse_the_open_interrupt[1] = {0u};

/** @brief Channels the refuse_the_open_software completions must arrive on, in order. */
static const uint8_t praet_order_refuse_the_open_software[1] = {0u};

/** @brief Calls the accept_the_open_refuse_the_submit case makes. */
static const PraetProgramStep praet_program_accept_the_open_refuse_the_submit[] = {
    {0u, 0u, 0u},
    {1u, 0u, 64u},
    {3u, 0u, 0u},
    {2u, 0u, 0u},
};

/** @brief Engine script for the accept_the_open_refuse_the_submit case. */
static const PraetEngineStep praet_steps_accept_the_open_refuse_the_submit[] = {
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u},
    {3u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {2u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
};

/** @brief Channels the accept_the_open_refuse_the_submit_interrupt completions must arrive on, in order. */
static const uint8_t praet_order_accept_the_open_refuse_the_submit_interrupt[1] = {0u};

/** @brief Channels the accept_the_open_refuse_the_submit_software completions must arrive on, in order. */
static const uint8_t praet_order_accept_the_open_refuse_the_submit_software[1] = {0u};

/** @brief Calls the accept_and_never_complete case makes. */
static const PraetProgramStep praet_program_accept_and_never_complete[] = {
    {0u, 0u, 0u},
    {1u, 0u, 64u},
    {3u, 0u, 0u},
    {2u, 0u, 0u},
};

/** @brief Engine script for the accept_and_never_complete case. */
static const PraetEngineStep praet_steps_accept_and_never_complete[] = {
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {1u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {3u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {2u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
};

/** @brief Channels the accept_and_never_complete_interrupt completions must arrive on, in order. */
static const uint8_t praet_order_accept_and_never_complete_interrupt[1] = {0u};

/** @brief Channels the accept_and_never_complete_software completions must arrive on, in order. */
static const uint8_t praet_order_accept_and_never_complete_software[1] = {0u};

/** @brief Calls the complete_inside_the_submit_call case makes. */
static const PraetProgramStep praet_program_complete_inside_the_submit_call[] = {
    {0u, 0u, 0u},
    {1u, 0u, 64u},
    {3u, 0u, 0u},
    {2u, 0u, 0u},
};

/** @brief Engine script for the complete_inside_the_submit_call case. */
static const PraetEngineStep praet_steps_complete_inside_the_submit_call[] = {
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {1u, 0u, 1u, 1u, 1u, 64u, 0u, 0u, 0u},
    {3u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {2u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
};

/** @brief Channels the complete_inside_the_submit_call_interrupt completions must arrive on, in order. */
static const uint8_t praet_order_complete_inside_the_submit_call_interrupt[] = {0u};

/** @brief Channels the complete_inside_the_submit_call_software completions must arrive on, in order. */
static const uint8_t praet_order_complete_inside_the_submit_call_software[] = {0u};

/** @brief Calls the complete_twice_for_one_transfer case makes. */
static const PraetProgramStep praet_program_complete_twice_for_one_transfer[] = {
    {0u, 0u, 0u},
    {1u, 0u, 64u},
    {3u, 0u, 0u},
    {2u, 0u, 0u},
};

/** @brief Engine script for the complete_twice_for_one_transfer case. */
static const PraetEngineStep praet_steps_complete_twice_for_one_transfer[] = {
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {1u, 0u, 1u, 2u, 2u, 64u, 0u, 0u, 0u},
    {3u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {2u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
};

/** @brief Channels the complete_twice_for_one_transfer_interrupt completions must arrive on, in order. */
static const uint8_t praet_order_complete_twice_for_one_transfer_interrupt[] = {0u, 0u};

/** @brief Channels the complete_twice_for_one_transfer_software completions must arrive on, in order. */
static const uint8_t praet_order_complete_twice_for_one_transfer_software[] = {0u, 0u};

/** @brief Calls the complete_twelve_of_sixty_four case makes. */
static const PraetProgramStep praet_program_complete_twelve_of_sixty_four[] = {
    {0u, 0u, 0u},
    {1u, 0u, 64u},
    {3u, 0u, 0u},
    {2u, 0u, 0u},
};

/** @brief Engine script for the complete_twelve_of_sixty_four case. */
static const PraetEngineStep praet_steps_complete_twelve_of_sixty_four[] = {
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {1u, 0u, 1u, 2u, 1u, 12u, 0u, 0u, 0u},
    {3u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {2u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
};

/** @brief Channels the complete_twelve_of_sixty_four_interrupt completions must arrive on, in order. */
static const uint8_t praet_order_complete_twelve_of_sixty_four_interrupt[] = {0u};

/** @brief Channels the complete_twelve_of_sixty_four_software completions must arrive on, in order. */
static const uint8_t praet_order_complete_twelve_of_sixty_four_software[] = {0u};

/** @brief Calls the complete_more_than_was_asked case makes. */
static const PraetProgramStep praet_program_complete_more_than_was_asked[] = {
    {0u, 0u, 0u},
    {1u, 0u, 64u},
    {3u, 0u, 0u},
    {2u, 0u, 0u},
};

/** @brief Engine script for the complete_more_than_was_asked case. */
static const PraetEngineStep praet_steps_complete_more_than_was_asked[] = {
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {1u, 0u, 1u, 2u, 1u, 100u, 0u, 0u, 0u},
    {3u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {2u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
};

/** @brief Channels the complete_more_than_was_asked_interrupt completions must arrive on, in order. */
static const uint8_t praet_order_complete_more_than_was_asked_interrupt[] = {0u};

/** @brief Channels the complete_more_than_was_asked_software completions must arrive on, in order. */
static const uint8_t praet_order_complete_more_than_was_asked_software[] = {0u};

/** @brief Calls the complete_after_the_close case makes. */
static const PraetProgramStep praet_program_complete_after_the_close[] = {
    {0u, 0u, 0u},
    {1u, 0u, 64u},
    {2u, 0u, 0u},
    {3u, 0u, 0u},
};

/** @brief Engine script for the complete_after_the_close case. */
static const PraetEngineStep praet_steps_complete_after_the_close[] = {
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {1u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {2u, 0u, 1u, 2u, 1u, 64u, 0u, 0u, 0u},
    {3u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
};

/** @brief Channels the complete_after_the_close_interrupt completions must arrive on, in order. */
static const uint8_t praet_order_complete_after_the_close_interrupt[] = {0u};

/** @brief Channels the complete_after_the_close_software completions must arrive on, in order. */
static const uint8_t praet_order_complete_after_the_close_software[] = {0u};

/** @brief Calls the complete_a_transfer_of_no_bytes case makes. */
static const PraetProgramStep praet_program_complete_a_transfer_of_no_bytes[] = {
    {0u, 0u, 0u},
    {1u, 0u, 0u},
    {3u, 0u, 0u},
    {2u, 0u, 0u},
};

/** @brief Engine script for the complete_a_transfer_of_no_bytes case. */
static const PraetEngineStep praet_steps_complete_a_transfer_of_no_bytes[] = {
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {1u, 0u, 1u, 2u, 1u, 0u, 0u, 0u, 0u},
    {3u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {2u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
};

/** @brief Channels the complete_a_transfer_of_no_bytes_interrupt completions must arrive on, in order. */
static const uint8_t praet_order_complete_a_transfer_of_no_bytes_interrupt[] = {0u};

/** @brief Channels the complete_a_transfer_of_no_bytes_software completions must arrive on, in order. */
static const uint8_t praet_order_complete_a_transfer_of_no_bytes_software[] = {0u};

/** @brief Calls the finish_channel_three_before_channel_one case makes. */
static const PraetProgramStep praet_program_finish_channel_three_before_channel_one[] = {
    {0u, 1u, 0u},
    {0u, 3u, 0u},
    {1u, 1u, 64u},
    {1u, 3u, 64u},
    {3u, 3u, 0u},
    {3u, 1u, 0u},
};

/** @brief Engine script for the finish_channel_three_before_channel_one case. */
static const PraetEngineStep praet_steps_finish_channel_three_before_channel_one[] = {
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {1u, 0u, 1u, 2u, 1u, 64u, 0u, 0u, 0u},
    {1u, 0u, 1u, 2u, 1u, 64u, 0u, 0u, 0u},
    {3u, 3u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {3u, 1u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
};

/** @brief Channels the finish_channel_three_before_channel_one_interrupt completions must arrive on, in order. */
static const uint8_t praet_order_finish_channel_three_before_channel_one_interrupt[] = {1u, 3u};

/** @brief Channels the finish_channel_three_before_channel_one_software completions must arrive on, in order. */
static const uint8_t praet_order_finish_channel_three_before_channel_one_software[] = {3u, 1u};

/** @brief Calls the eight_logical_channels_on_one_engine case makes. */
static const PraetProgramStep praet_program_eight_logical_channels_on_one_engine[] = {
    {0u, 0u, 0u},
    {0u, 1u, 0u},
    {0u, 2u, 0u},
    {0u, 3u, 0u},
    {0u, 4u, 0u},
    {0u, 5u, 0u},
    {0u, 6u, 0u},
    {0u, 7u, 0u},
    {1u, 0u, 16u},
    {1u, 1u, 16u},
    {1u, 2u, 16u},
    {1u, 3u, 16u},
    {1u, 4u, 16u},
    {1u, 5u, 16u},
    {1u, 6u, 16u},
    {1u, 7u, 16u},
    {3u, 0u, 0u},
};

/** @brief Engine script for the eight_logical_channels_on_one_engine case. */
static const PraetEngineStep praet_steps_eight_logical_channels_on_one_engine[] = {
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {1u, 0u, 1u, 2u, 1u, 16u, 0u, 0u, 0u},
    {1u, 0u, 1u, 2u, 1u, 16u, 0u, 0u, 0u},
    {1u, 0u, 1u, 2u, 1u, 16u, 0u, 0u, 0u},
    {1u, 0u, 1u, 2u, 1u, 16u, 0u, 0u, 0u},
    {1u, 0u, 1u, 2u, 1u, 16u, 0u, 0u, 0u},
    {1u, 0u, 1u, 2u, 1u, 16u, 0u, 0u, 0u},
    {1u, 0u, 1u, 2u, 1u, 16u, 0u, 0u, 0u},
    {1u, 0u, 1u, 2u, 1u, 16u, 0u, 0u, 0u},
    {3u, 255u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
};

/** @brief Channels the eight_logical_channels_on_one_engine_interrupt completions must arrive on, in order. */
static const uint8_t praet_order_eight_logical_channels_on_one_engine_interrupt[] = {0u, 1u, 2u, 3u, 4u, 5u, 6u, 7u};

/** @brief Channels the eight_logical_channels_on_one_engine_software completions must arrive on, in order. */
static const uint8_t praet_order_eight_logical_channels_on_one_engine_software[] = {0u, 1u, 2u, 3u, 4u, 5u, 6u, 7u};

/** @brief Calls the submit_before_the_channel_has_settled case makes. */
static const PraetProgramStep praet_program_submit_before_the_channel_has_settled[] = {
    {0u, 0u, 0u},
    {1u, 0u, 64u},
    {3u, 0u, 0u},
    {2u, 0u, 0u},
};

/** @brief Engine script for the submit_before_the_channel_has_settled case. */
static const PraetEngineStep praet_steps_submit_before_the_channel_has_settled[] = {
    {0u, 0u, 1u, 0u, 0u, 0u, 3u, 0u, 0u},
    {1u, 0u, 1u, 2u, 1u, 64u, 0u, 0u, 0u},
    {3u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {2u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
};

/** @brief Channels the submit_before_the_channel_has_settled_interrupt completions must arrive on, in order. */
static const uint8_t praet_order_submit_before_the_channel_has_settled_interrupt[1] = {0u};

/** @brief Channels the submit_before_the_channel_has_settled_software completions must arrive on, in order. */
static const uint8_t praet_order_submit_before_the_channel_has_settled_software[1] = {0u};

/** @brief Calls the submit_after_the_channel_has_settled case makes. */
static const PraetProgramStep praet_program_submit_after_the_channel_has_settled[] = {
    {0u, 0u, 0u},
    {3u, 0u, 0u},
    {3u, 0u, 0u},
    {1u, 0u, 64u},
    {3u, 0u, 0u},
    {2u, 0u, 0u},
};

/** @brief Engine script for the submit_after_the_channel_has_settled case. */
static const PraetEngineStep praet_steps_submit_after_the_channel_has_settled[] = {
    {0u, 0u, 1u, 0u, 0u, 0u, 3u, 0u, 0u},
    {3u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {3u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {1u, 0u, 1u, 2u, 1u, 64u, 0u, 0u, 0u},
    {3u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {2u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
};

/** @brief Channels the submit_after_the_channel_has_settled_interrupt completions must arrive on, in order. */
static const uint8_t praet_order_submit_after_the_channel_has_settled_interrupt[] = {0u};

/** @brief Channels the submit_after_the_channel_has_settled_software completions must arrive on, in order. */
static const uint8_t praet_order_submit_after_the_channel_has_settled_software[] = {0u};

/** @brief Calls the due_on_the_close_with_no_poll_after case makes. */
static const PraetProgramStep praet_program_due_on_the_close_with_no_poll_after[] = {
    {0u, 0u, 0u},
    {1u, 0u, 64u},
    {2u, 0u, 0u},
};

/** @brief Engine script for the due_on_the_close_with_no_poll_after case. */
static const PraetEngineStep praet_steps_due_on_the_close_with_no_poll_after[] = {
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {1u, 0u, 1u, 2u, 1u, 64u, 0u, 1u, 0u},
    {2u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
};

/** @brief Channels the due_on_the_close_with_no_poll_after_interrupt completions must arrive on, in order. */
static const uint8_t praet_order_due_on_the_close_with_no_poll_after_interrupt[] = {0u};

/** @brief Channels the due_on_the_close_with_no_poll_after_software completions must arrive on, in order. */
static const uint8_t praet_order_due_on_the_close_with_no_poll_after_software[1] = {0u};

/** @brief Calls the the_shorter_transfer_finishes_first case makes. */
static const PraetProgramStep praet_program_the_shorter_transfer_finishes_first[] = {
    {0u, 1u, 0u},
    {0u, 3u, 0u},
    {1u, 1u, 64u},
    {1u, 3u, 64u},
    {3u, 255u, 0u},
    {3u, 255u, 0u},
    {3u, 255u, 0u},
};

/** @brief Engine script for the the_shorter_transfer_finishes_first case. */
static const PraetEngineStep praet_steps_the_shorter_transfer_finishes_first[] = {
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {1u, 0u, 1u, 2u, 1u, 64u, 0u, 4u, 0u},
    {1u, 0u, 1u, 2u, 1u, 64u, 0u, 0u, 0u},
    {3u, 255u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {3u, 255u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {3u, 255u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
};

/** @brief Channels the the_shorter_transfer_finishes_first_interrupt completions must arrive on, in order. */
static const uint8_t praet_order_the_shorter_transfer_finishes_first_interrupt[] = {3u, 1u};

/** @brief Channels the the_shorter_transfer_finishes_first_software completions must arrive on, in order. */
static const uint8_t praet_order_the_shorter_transfer_finishes_first_software[] = {3u, 1u};

/** @brief Calls the polled_before_the_cycle_elapsed case makes. */
static const PraetProgramStep praet_program_polled_before_the_cycle_elapsed[] = {
    {0u, 0u, 0u},
    {1u, 0u, 64u},
    {3u, 0u, 0u},
    {2u, 0u, 0u},
};

/** @brief Engine script for the polled_before_the_cycle_elapsed case. */
static const PraetEngineStep praet_steps_polled_before_the_cycle_elapsed[] = {
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {1u, 0u, 1u, 2u, 1u, 64u, 0u, 8u, 0u},
    {3u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
    {2u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u},
};

/** @brief Channels the polled_before_the_cycle_elapsed_interrupt completions must arrive on, in order. */
static const uint8_t praet_order_polled_before_the_cycle_elapsed_interrupt[1] = {0u};

/** @brief Channels the polled_before_the_cycle_elapsed_software completions must arrive on, in order. */
static const uint8_t praet_order_polled_before_the_cycle_elapsed_software[1] = {0u};

/**
 * @brief Every correctness scenario, on both arms, control first.
 *
 * @note One row per scenario per arm, each carrying its program, its script, and the
 *       outcome the two must produce together. The suite walks this table in order.
 */
static const PraetScenario praet_scenarios[] = {
    {
        "control_one_transfer_completes_interrupt",
        0u,
        praet_program_control_one_transfer_completes,
        4u,
        praet_steps_control_one_transfer_completes,
        4u,
        1u,
        1u,
        1u,
        64uL,
        0u,
        0u,
        praet_order_control_one_transfer_completes_interrupt,
        1u,
    },
    {
        "control_one_transfer_completes_software",
        1u,
        praet_program_control_one_transfer_completes,
        4u,
        praet_steps_control_one_transfer_completes,
        4u,
        1u,
        1u,
        1u,
        64uL,
        0u,
        0u,
        praet_order_control_one_transfer_completes_software,
        1u,
    },
    {
        "refuse_the_open_interrupt",
        0u,
        praet_program_refuse_the_open,
        4u,
        praet_steps_refuse_the_open,
        4u,
        0u,
        0u,
        0u,
        0uL,
        0u,
        0u,
        praet_order_refuse_the_open_interrupt,
        0u,
    },
    {
        "refuse_the_open_software",
        1u,
        praet_program_refuse_the_open,
        4u,
        praet_steps_refuse_the_open,
        4u,
        0u,
        0u,
        0u,
        0uL,
        0u,
        0u,
        praet_order_refuse_the_open_software,
        0u,
    },
    {
        "accept_the_open_refuse_the_submit_interrupt",
        0u,
        praet_program_accept_the_open_refuse_the_submit,
        4u,
        praet_steps_accept_the_open_refuse_the_submit,
        4u,
        1u,
        0u,
        0u,
        0uL,
        0u,
        0u,
        praet_order_accept_the_open_refuse_the_submit_interrupt,
        0u,
    },
    {
        "accept_the_open_refuse_the_submit_software",
        1u,
        praet_program_accept_the_open_refuse_the_submit,
        4u,
        praet_steps_accept_the_open_refuse_the_submit,
        4u,
        1u,
        0u,
        0u,
        0uL,
        0u,
        0u,
        praet_order_accept_the_open_refuse_the_submit_software,
        0u,
    },
    {
        "accept_and_never_complete_interrupt",
        0u,
        praet_program_accept_and_never_complete,
        4u,
        praet_steps_accept_and_never_complete,
        4u,
        1u,
        1u,
        0u,
        0uL,
        0u,
        0u,
        praet_order_accept_and_never_complete_interrupt,
        0u,
    },
    {
        "accept_and_never_complete_software",
        1u,
        praet_program_accept_and_never_complete,
        4u,
        praet_steps_accept_and_never_complete,
        4u,
        1u,
        1u,
        0u,
        0uL,
        0u,
        0u,
        praet_order_accept_and_never_complete_software,
        0u,
    },
    {
        "complete_inside_the_submit_call_interrupt",
        0u,
        praet_program_complete_inside_the_submit_call,
        4u,
        praet_steps_complete_inside_the_submit_call,
        4u,
        1u,
        1u,
        1u,
        64uL,
        0u,
        0u,
        praet_order_complete_inside_the_submit_call_interrupt,
        1u,
    },
    {
        "complete_inside_the_submit_call_software",
        1u,
        praet_program_complete_inside_the_submit_call,
        4u,
        praet_steps_complete_inside_the_submit_call,
        4u,
        1u,
        1u,
        1u,
        64uL,
        0u,
        0u,
        praet_order_complete_inside_the_submit_call_software,
        1u,
    },
    {
        "complete_twice_for_one_transfer_interrupt",
        0u,
        praet_program_complete_twice_for_one_transfer,
        4u,
        praet_steps_complete_twice_for_one_transfer,
        4u,
        1u,
        1u,
        2u,
        128uL,
        0u,
        0u,
        praet_order_complete_twice_for_one_transfer_interrupt,
        2u,
    },
    {
        "complete_twice_for_one_transfer_software",
        1u,
        praet_program_complete_twice_for_one_transfer,
        4u,
        praet_steps_complete_twice_for_one_transfer,
        4u,
        1u,
        1u,
        2u,
        128uL,
        0u,
        0u,
        praet_order_complete_twice_for_one_transfer_software,
        2u,
    },
    {
        "complete_twelve_of_sixty_four_interrupt",
        0u,
        praet_program_complete_twelve_of_sixty_four,
        4u,
        praet_steps_complete_twelve_of_sixty_four,
        4u,
        1u,
        1u,
        1u,
        12uL,
        0u,
        0u,
        praet_order_complete_twelve_of_sixty_four_interrupt,
        1u,
    },
    {
        "complete_twelve_of_sixty_four_software",
        1u,
        praet_program_complete_twelve_of_sixty_four,
        4u,
        praet_steps_complete_twelve_of_sixty_four,
        4u,
        1u,
        1u,
        1u,
        12uL,
        0u,
        0u,
        praet_order_complete_twelve_of_sixty_four_software,
        1u,
    },
    {
        "complete_more_than_was_asked_interrupt",
        0u,
        praet_program_complete_more_than_was_asked,
        4u,
        praet_steps_complete_more_than_was_asked,
        4u,
        1u,
        1u,
        1u,
        100uL,
        0u,
        0u,
        praet_order_complete_more_than_was_asked_interrupt,
        1u,
    },
    {
        "complete_more_than_was_asked_software",
        1u,
        praet_program_complete_more_than_was_asked,
        4u,
        praet_steps_complete_more_than_was_asked,
        4u,
        1u,
        1u,
        1u,
        100uL,
        0u,
        0u,
        praet_order_complete_more_than_was_asked_software,
        1u,
    },
    {
        "complete_after_the_close_interrupt",
        0u,
        praet_program_complete_after_the_close,
        4u,
        praet_steps_complete_after_the_close,
        4u,
        1u,
        1u,
        1u,
        64uL,
        0u,
        0u,
        praet_order_complete_after_the_close_interrupt,
        1u,
    },
    {
        "complete_after_the_close_software",
        1u,
        praet_program_complete_after_the_close,
        4u,
        praet_steps_complete_after_the_close,
        4u,
        1u,
        1u,
        1u,
        64uL,
        0u,
        0u,
        praet_order_complete_after_the_close_software,
        1u,
    },
    {
        "complete_a_transfer_of_no_bytes_interrupt",
        0u,
        praet_program_complete_a_transfer_of_no_bytes,
        4u,
        praet_steps_complete_a_transfer_of_no_bytes,
        4u,
        1u,
        1u,
        1u,
        0uL,
        0u,
        0u,
        praet_order_complete_a_transfer_of_no_bytes_interrupt,
        1u,
    },
    {
        "complete_a_transfer_of_no_bytes_software",
        1u,
        praet_program_complete_a_transfer_of_no_bytes,
        4u,
        praet_steps_complete_a_transfer_of_no_bytes,
        4u,
        1u,
        1u,
        1u,
        0uL,
        0u,
        0u,
        praet_order_complete_a_transfer_of_no_bytes_software,
        1u,
    },
    {
        "finish_channel_three_before_channel_one_interrupt",
        0u,
        praet_program_finish_channel_three_before_channel_one,
        6u,
        praet_steps_finish_channel_three_before_channel_one,
        6u,
        2u,
        2u,
        2u,
        128uL,
        0u,
        0u,
        praet_order_finish_channel_three_before_channel_one_interrupt,
        2u,
    },
    {
        "finish_channel_three_before_channel_one_software",
        1u,
        praet_program_finish_channel_three_before_channel_one,
        6u,
        praet_steps_finish_channel_three_before_channel_one,
        6u,
        2u,
        2u,
        2u,
        128uL,
        0u,
        0u,
        praet_order_finish_channel_three_before_channel_one_software,
        2u,
    },
    {
        "eight_logical_channels_on_one_engine_interrupt",
        0u,
        praet_program_eight_logical_channels_on_one_engine,
        17u,
        praet_steps_eight_logical_channels_on_one_engine,
        17u,
        8u,
        8u,
        8u,
        128uL,
        0u,
        0u,
        praet_order_eight_logical_channels_on_one_engine_interrupt,
        8u,
    },
    {
        "eight_logical_channels_on_one_engine_software",
        1u,
        praet_program_eight_logical_channels_on_one_engine,
        17u,
        praet_steps_eight_logical_channels_on_one_engine,
        17u,
        8u,
        8u,
        8u,
        128uL,
        0u,
        0u,
        praet_order_eight_logical_channels_on_one_engine_software,
        8u,
    },
    {
        "submit_before_the_channel_has_settled_interrupt",
        0u,
        praet_program_submit_before_the_channel_has_settled,
        4u,
        praet_steps_submit_before_the_channel_has_settled,
        4u,
        1u,
        0u,
        0u,
        0uL,
        1u,
        0u,
        praet_order_submit_before_the_channel_has_settled_interrupt,
        0u,
    },
    {
        "submit_before_the_channel_has_settled_software",
        1u,
        praet_program_submit_before_the_channel_has_settled,
        4u,
        praet_steps_submit_before_the_channel_has_settled,
        4u,
        1u,
        0u,
        0u,
        0uL,
        1u,
        0u,
        praet_order_submit_before_the_channel_has_settled_software,
        0u,
    },
    {
        "submit_after_the_channel_has_settled_interrupt",
        0u,
        praet_program_submit_after_the_channel_has_settled,
        6u,
        praet_steps_submit_after_the_channel_has_settled,
        6u,
        1u,
        1u,
        1u,
        64uL,
        0u,
        0u,
        praet_order_submit_after_the_channel_has_settled_interrupt,
        1u,
    },
    {
        "submit_after_the_channel_has_settled_software",
        1u,
        praet_program_submit_after_the_channel_has_settled,
        6u,
        praet_steps_submit_after_the_channel_has_settled,
        6u,
        1u,
        1u,
        1u,
        64uL,
        0u,
        0u,
        praet_order_submit_after_the_channel_has_settled_software,
        1u,
    },
    {
        "due_on_the_close_with_no_poll_after_interrupt",
        0u,
        praet_program_due_on_the_close_with_no_poll_after,
        3u,
        praet_steps_due_on_the_close_with_no_poll_after,
        3u,
        1u,
        1u,
        1u,
        64uL,
        0u,
        0u,
        praet_order_due_on_the_close_with_no_poll_after_interrupt,
        1u,
    },
    {
        "due_on_the_close_with_no_poll_after_software",
        1u,
        praet_program_due_on_the_close_with_no_poll_after,
        3u,
        praet_steps_due_on_the_close_with_no_poll_after,
        3u,
        1u,
        1u,
        0u,
        0uL,
        0u,
        1u,
        praet_order_due_on_the_close_with_no_poll_after_software,
        0u,
    },
    {
        "the_shorter_transfer_finishes_first_interrupt",
        0u,
        praet_program_the_shorter_transfer_finishes_first,
        7u,
        praet_steps_the_shorter_transfer_finishes_first,
        7u,
        2u,
        2u,
        2u,
        128uL,
        0u,
        0u,
        praet_order_the_shorter_transfer_finishes_first_interrupt,
        2u,
    },
    {
        "the_shorter_transfer_finishes_first_software",
        1u,
        praet_program_the_shorter_transfer_finishes_first,
        7u,
        praet_steps_the_shorter_transfer_finishes_first,
        7u,
        2u,
        2u,
        2u,
        128uL,
        0u,
        0u,
        praet_order_the_shorter_transfer_finishes_first_software,
        2u,
    },
    {
        "polled_before_the_cycle_elapsed_interrupt",
        0u,
        praet_program_polled_before_the_cycle_elapsed,
        4u,
        praet_steps_polled_before_the_cycle_elapsed,
        4u,
        1u,
        1u,
        0u,
        0uL,
        0u,
        1u,
        praet_order_polled_before_the_cycle_elapsed_interrupt,
        0u,
    },
    {
        "polled_before_the_cycle_elapsed_software",
        1u,
        praet_program_polled_before_the_cycle_elapsed,
        4u,
        praet_steps_polled_before_the_cycle_elapsed,
        4u,
        1u,
        1u,
        0u,
        0uL,
        0u,
        1u,
        praet_order_polled_before_the_cycle_elapsed_software,
        0u,
    },
};

EMBED_END_DECLS

#endif
