/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "bitorum_introitus_exitus/bitorum_introitus_exitus.h"
#include <stdint.h>
#include <stdio.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_the_exact_packing_this_suite_relies_on_is_itself_right(void);
extern void test_a_single_put_of_every_width_lands_where_the_reference_puts_it(void);
extern void test_a_run_of_puts_across_byte_boundaries_lands_where_the_reference_puts_it(void);
extern void test_the_bits_read_back_out_rebuild_the_values_that_were_written(void);
extern void test_align_pads_the_last_byte_with_zeros_above_the_bits_written(void);
extern void test_a_put_of_no_bits_moves_nothing(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/accuracy/test_bitorum_introitus_exitus_accuracy\\test_bitorum_introitus_exitus_accuracy.c");
  run_test(test_the_exact_packing_this_suite_relies_on_is_itself_right, "test_the_exact_packing_this_suite_relies_on_is_itself_right", 215);
  run_test(test_a_single_put_of_every_width_lands_where_the_reference_puts_it, "test_a_single_put_of_every_width_lands_where_the_reference_puts_it", 246);
  run_test(test_a_run_of_puts_across_byte_boundaries_lands_where_the_reference_puts_it, "test_a_run_of_puts_across_byte_boundaries_lands_where_the_reference_puts_it", 303);
  run_test(test_the_bits_read_back_out_rebuild_the_values_that_were_written, "test_the_bits_read_back_out_rebuild_the_values_that_were_written", 354);
  run_test(test_align_pads_the_last_byte_with_zeros_above_the_bits_written, "test_align_pads_the_last_byte_with_zeros_above_the_bits_written", 405);
  run_test(test_a_put_of_no_bits_moves_nothing, "test_a_put_of_no_bits_moves_nothing", 446);

  return UNITY_END();
}
