/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "pow5/pow5.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_the_exact_arithmetic_this_suite_relies_on_is_itself_right(void);
extern void test_every_positive_power_of_five_is_the_top_128_bits_of_the_exact_value(void);
extern void test_the_first_six_positive_powers_lose_no_bits_at_all(void);
extern void test_the_last_three_positive_powers_drop_bits_and_drop_them_downward(void);
extern void test_every_negative_power_of_five_is_the_exact_reciprocal_truncated_toward_zero(void);
extern void test_no_reciprocal_was_rounded_up(void);
extern void test_the_reciprocal_of_five_repeats_rather_than_rounding(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/mmgrwork/MMgr/test/accuracy/test_pow5_accuracy\\test_pow5_accuracy.c");
  run_test(test_the_exact_arithmetic_this_suite_relies_on_is_itself_right, "test_the_exact_arithmetic_this_suite_relies_on_is_itself_right", 235);
  run_test(test_every_positive_power_of_five_is_the_top_128_bits_of_the_exact_value, "test_every_positive_power_of_five_is_the_top_128_bits_of_the_exact_value", 262);
  run_test(test_the_first_six_positive_powers_lose_no_bits_at_all, "test_the_first_six_positive_powers_lose_no_bits_at_all", 284);
  run_test(test_the_last_three_positive_powers_drop_bits_and_drop_them_downward, "test_the_last_three_positive_powers_drop_bits_and_drop_them_downward", 296);
  run_test(test_every_negative_power_of_five_is_the_exact_reciprocal_truncated_toward_zero, "test_every_negative_power_of_five_is_the_exact_reciprocal_truncated_toward_zero", 312);
  run_test(test_no_reciprocal_was_rounded_up, "test_no_reciprocal_was_rounded_up", 345);
  run_test(test_the_reciprocal_of_five_repeats_rather_than_rounding, "test_the_reciprocal_of_five_repeats_rather_than_rounding", 374);

  return UNITY_END();
}
